const assert=require('node:assert/strict'),E=require('../app/engine.js'),A=require('../app/action.js')(E);
const run=(p,s,n,input={})=>{for(let i=0;i<n;i++)A.tick(p,s,1/60,input);};
let p=A.sample();E.validate(p);const original=JSON.stringify(p);let s=A.create(p);run(p,s,30);assert(s.grounded);assert.equal(s.py,512);const x=s.px;run(p,s,12,{right:true});assert(s.px>x);A.tick(p,s,1/60,{jump:true});assert(s.vy<0);run(p,s,80);assert(s.grounded);assert.equal(JSON.stringify(p),original);
// A wall blocks the body, not just its feet; the low ceiling prevents tunnelling.
p=A.sample();p.maps[0].enemies=[];const m=p.maps[0];for(let y=9;y<16;y++)m.collision[y*m.w+5]=true;s=A.create(p);run(p,s,100,{right:true});assert(s.px+12<=5*32+.01);s=A.create(p);run(p,s,1);m.collision[12*m.w+3]=true;A.tick(p,s,1/60,{jump:true});run(p,s,8);assert(s.py-76>=13*32-.01);
// Grab -> frozen actions -> distinct X presses -> release immunity and timeout.
p=A.sample();p.maps[0].enemies=[{...A.enemy(3,15),speed:0,damage:1,hold:1,escape:3}];s=A.create(p);run(p,s,1);assert(s.grab);assert.equal(s.hp,4);const capturedX=s.px;run(p,s,10,{right:true,jump:true,attack:true});assert.equal(s.px,capturedX);assert.equal(s.attack,0);for(let i=0;i<3;i++)A.tick(p,s,1/60,{escape:true});assert.equal(s.grab,null);assert(s.invincible>0);run(p,s,2);assert.equal(s.grab,null);s=A.create(p);run(p,s,65);assert.equal(s.grab,null);
// Attack damages each enemy once per swing, defeat no longer grabs.
p=A.sample();p.maps[0].enemies=[{...A.enemy(4,15),speed:0,canGrab:false,damage:0,hp:2}];s=A.create(p);A.tick(p,s,1/60,{attack:true});run(p,s,8);assert.equal(s.enemyMaps.cliff[0].hp,1);run(p,s,20);A.tick(p,s,1/60,{attack:true});assert.equal(s.enemyMaps.cliff[0].hp,0);
// Death, fall, transfer reset, retained map-local enemy state.
p=A.sample();p.maps[0].enemies=[];s=A.create(p);s.py=p.maps[0].h*32+200;A.tick(p,s,1/60);assert(s.dead);assert.equal(s.hp,0);p.maps.push(A.map('Second',20,18));s=A.create(p);s.map=p.maps[1].id;s.x=2;s.y=15;s.grab={id:'old'};A.enter(p,s);assert.equal(s.px,80);assert.equal(s.grab,null);assert.equal(s.enemyMaps[s.map].length,0);
// Conditions are edge-triggered, expire, hide when false, and reset on retrigger.
p=A.sample();const data='data:image/png;base64,iVBORw0KGgo=';p.assets=[{id:'motion',kind:'animation',name:'Test',data,cols:2,rows:1,frames:2,fps:8}];p.effects=[{id:'f',asset:'motion',when:'switch',key:'show',threshold:1,map:'',x:10,y:20,width:30,height:40,opacity:1,duration:.5,loop:true}];E.validate(p);s=A.create(p);assert(!A.condition(p.effects[0],p,s));s.switches.show=true;assert(A.condition(p.effects[0],p,s));const ctx={save(){},restore(){}};global.Image=class{complete=false;};A.effects(ctx,p,s,640,360,.2);assert.equal(s.effectState.f.time,.2);A.effects(ctx,p,s,640,360,.4);assert(s.effectState.f.time>.5);s.switches.show=false;A.effects(ctx,p,s,640,360,.1);s.switches.show=true;A.effects(ctx,p,s,640,360,.1);assert.equal(s.effectState.f.time,.1);delete global.Image;
const round=JSON.parse(JSON.stringify(p));assert.deepEqual(E.validate(round),p);assert.throws(()=>E.validate({...p,effects:[{...p.effects[0],asset:'missing'}]}));assert.throws(()=>E.validate({...p,action:{...p.action,width:NaN}}));assert.throws(()=>E.validate({...p,assets:[{...p.assets[0],frames:9}]}));assert.throws(()=>E.validate({...p,mode:'unknown'}));
E.validate(E.sample());console.log('PASS: action movement, floor/wall/ceiling collision, jump, capture/frozen controls, escape/timeout/immunity, combat, death, map state, effects/retrigger, schema and legacy projects');
