const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
(async()=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'sf-media-')),browser=await chromium.launch({executablePath:process.env.CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage'],headless:true});try{
const page=await browser.newPage({viewport:{width:1480,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://'+path.resolve('app/index.html'));await page.locator('#actionExample').click();await page.locator('#confirmAction').click();
const gif=path.join(temp,'timing.gif');fs.writeFileSync(gif,Buffer.from('R0lGODlhDAAUAIEAAP8AAAAAAAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh+QQICgAAACwAAAAADAAUAAAIGwABCBxIsKDBgwgTKlzIsKHDhxAjSpxIsWLCgAAh+QQIHgAAACwAAAAADAAUAIEAAP8AAAAAAAAAAAAIGwABCBxIsKDBgwgTKlzIsKHDhxAjSpxIsWLCgAA7','base64'));
await page.locator('#motionFile').setInputFiles(gif);await page.locator('#addGif').waitFor();await page.locator('#addGif').click();let a=await page.evaluate(()=>P.assets.at(-1));assert.deepEqual(a.frameDurations,[.1,.3]);assert.equal(a.frames,2);const gifId=a.id;
// Canvas must display both decoded frames, keep original timing and stop on the last frame.
const pixels=await page.evaluate(async id=>{const a=P.assets.find(a=>a.id===id),im=new Image();im.src=a.data;await im.decode();const cv=document.createElement('canvas');cv.width=12;cv.height=20;const ctx=cv.getContext('2d');A.frame(ctx,P,id,0,0,12,20,0);await new Promise(r=>setTimeout(r,30));return [.05,.2,.45,10].map((t,i)=>{ctx.clearRect(0,0,12,20);A.frame(ctx,P,id,0,0,12,20,t,i!==3);return [...ctx.getImageData(5,5,1,1).data];});},gifId);assert.deepEqual(pixels,[[255,0,0,255],[0,0,255,255],[255,0,0,255],[0,0,255,255]]);
await page.locator('#actorSettings').click();await page.locator('[data-clip="healCast"]').selectOption(gifId);await page.locator('[data-clip="heal"]').selectOption(gifId);await page.locator('[data-config="healCastTime"]').fill('0.3');await page.locator('#applyActor').click();
// WAV is accepted, decoded, previewed and attached; spy on play without replacing Audio decoding.
const wav=path.join(temp,'test.wav'),buf=Buffer.alloc(44+1600);buf.write('RIFF');buf.writeUInt32LE(buf.length-8,4);buf.write('WAVEfmt ',8);buf.writeUInt32LE(16,16);buf.writeUInt16LE(1,20);buf.writeUInt16LE(1,22);buf.writeUInt32LE(8000,24);buf.writeUInt32LE(16000,28);buf.writeUInt16LE(2,32);buf.writeUInt16LE(16,34);buf.write('data',36);buf.writeUInt32LE(1600,40);fs.writeFileSync(wav,buf);
await page.locator('#soundSettings').click();await page.locator('#wavFile').setInputFiles(wav);await page.locator('[data-listen]').waitFor();await page.locator('[data-listen]').click();await page.waitForFunction(()=>document.querySelector('#toast').textContent!=='효과음을 재생할 수 없어요.');const sound=await page.locator('[data-listen]').getAttribute('data-listen');for(const k of ['attack','healCast','heal'])await page.locator(`[data-sound="${k}"]`).selectOption(sound);await page.locator('#applySounds').click();
await page.locator('#keySettings').click();await page.locator('[data-bind="heal"][data-slot="0"]').click();await page.keyboard.press('h');await page.locator('[data-bind="attack"][data-slot="0"]').click();await page.keyboard.press('k');await page.locator('#applyKeys').click();assert.deepEqual(await page.evaluate(()=>P.controls.heal),['KeyH']);
await page.locator('#assetFile').setInputFiles(gif);await page.locator('#gifKind').selectOption('background');await page.locator('#addGif').click();const bgId=await page.evaluate(()=>P.assets.at(-1).id);await page.locator('#backgroundSettings').click();await page.locator('#adjustBG').selectOption(bgId);await page.locator('#adjustSpace').selectOption('map');await page.locator('#bgFit').selectOption('cover');await page.locator('[data-bg="x"]').fill('10');await page.locator('[data-bg="scale"]').fill('150');await page.locator('[data-bg="opacity"]').fill('0.5');await page.locator('#applyBG').click();assert.equal(await page.evaluate(()=>map().backgroundAdjust.scale),150);await page.locator('#undo').click();assert.equal(await page.evaluate(()=>map().backgroundAdjust),undefined);await page.locator('#redo').click();
const round=await page.evaluate(()=>JSON.stringify(P));await page.evaluate(t=>loadText(t),round);assert.equal(await page.evaluate(()=>P.sounds.length),1);assert.equal(await page.evaluate(()=>P.maps[0].backgroundAdjust.x),10);
await page.evaluate(()=>{map().enemies=[];map().events=[];window.soundPlays=0;const original=HTMLMediaElement.prototype.play;HTMLMediaElement.prototype.play=function(){window.soundPlays++;return original.call(this);};});await page.locator('#play').click();await page.waitForFunction(()=>actionRuntime?.state.grounded);await page.evaluate(()=>actionRuntime.state.hp=1);await page.keyboard.press('c');await page.waitForTimeout(80);assert.equal(await page.evaluate(()=>actionRuntime.state.healCast),0);await page.keyboard.press('h');await page.waitForFunction(()=>actionRuntime.state.healCast>0);assert.equal(await page.evaluate(()=>actionRuntime.state.anim),'healCast');await page.waitForFunction(()=>actionRuntime.state.healing>0);assert.equal(await page.evaluate(()=>actionRuntime.state.hp),3);await page.waitForTimeout(500);assert.equal(await page.evaluate(()=>window.soundPlays),2);await page.keyboard.press('k');await page.waitForTimeout(100);assert.equal(await page.evaluate(()=>window.soundPlays),3);await page.waitForTimeout(300);await page.locator('[data-action="heal"]').click();await page.waitForFunction(()=>actionRuntime.state.hp===5);await page.keyboard.press('Escape');
const html=await page.evaluate(()=>exportHTML()),exportPath=path.join(temp,'game.html');fs.writeFileSync(exportPath,html);assert(html.includes('data:audio/wav;base64,'));assert(html.includes('frameDurations'));const game=await browser.newPage();game.on('pageerror',e=>errors.push(e.message));await game.goto('file://'+exportPath);await game.locator('[data-action="heal"]').waitFor();assert.match(await game.locator('.actionControls span').innerText(),/H 회복/);await game.keyboard.press('k');await game.waitForTimeout(100);
// Topdown keyboard remapping and legacy event dialogue remain functional in unified runtime.
await page.evaluate(()=>{P=E.sample();P.controls={...E.defaultControls(P),interact:['KeyQ']};mapId=P.start.map;render();});await page.locator('#play').click();await page.evaluate(()=>Object.assign(actionRuntime.state,{x:4,y:11,dir:3}));await page.keyboard.press('q');await page.waitForFunction(()=>actionRuntime.state.dialog?.text.includes('열쇠'));await page.keyboard.press('q');assert.equal(await page.evaluate(()=>actionRuntime.state.inventory['오래된 열쇠']),1);await page.keyboard.press('Escape');assert.deepEqual(errors,[]);
console.log('PASS: real GIF import/frames/timings, WAV decode/play and one-shot sounds, custom physical keys, healing state/HP/touch, background undo, save roundtrip, standalone HTML, legacy topdown dialogue');
}finally{await browser.close();fs.rmSync(temp,{recursive:true,force:true});}})().catch(e=>{console.error(e);process.exit(1);});
