const assert=require('node:assert/strict'),E=require('../app/engine.js'),A=require('../app/action.js')(E);
const run=(p,s,n,input={})=>{for(let i=0;i<n;i++)A.tick(p,s,1/60,input);};
let p=A.sample();p.maps[0].enemies=[];let s=A.create(p);run(p,s,2);s.hp=1;A.tick(p,s,1/60,{heal:true});assert.equal(s.anim,'healCast');const x=s.px;run(p,s,30,{attack:true,right:true,jump:true});assert.equal(s.px,x);assert.equal(s.attack,0);assert.equal(s.hp,1);run(p,s,31);assert.equal(s.hp,3);assert.equal(s.anim,'heal');run(p,s,35);assert.equal(s.anim,'idle');s.hp=4;A.tick(p,s,1/60,{heal:true});run(p,s,65);assert.equal(s.hp,5);run(p,s,40);A.tick(p,s,1/60,{heal:true});assert.equal(s.healCast,0);
// Damage interrupts casting, and capture blocks healing until release.
p=A.sample();p.maps[0].enemies=[];s=A.create(p);run(p,s,2);s.hp=3;A.tick(p,s,1/60,{heal:true});s.enemyMaps[s.map].push({...A.enemy(3,15),px:s.px,py:s.py,origin:s.px,vy:0,facing:-1,cooldown:0,hurt:0,hit:0,anim:'idle',speed:0});run(p,s,1);assert.equal(s.grab,null);assert.equal(s.anim,'hurt');assert.equal(s.healCast,0);run(p,s,15,{heal:true});assert.equal(s.hp,2);assert.equal(s.healCast,0);
const a={id:'gif',kind:'animation',data:'data:image/png;base64,AAAA',cols:2,rows:1,frames:2,fps:8,frameDurations:[.1,.3]};assert.equal(E.frameIndex(a,.05),0);assert.equal(E.frameIndex(a,.2),1);assert.equal(E.frameIndex(a,.45),0);assert.equal(E.frameIndex(a,10,false),1);
p=A.sample();p.assets=[a];p.action.clips.healCast=a.id;p.action.clips.heal=a.id;p.sounds=[{id:'sfx',name:'test',data:'data:audio/wav;base64,AAAA',volume:.5}];p.soundBindings={heal:'sfx'};p.controls={...E.defaultControls(p),heal:['KeyH']};p.maps[0].backgroundAdjust={fit:'cover',x:10,y:-5,scale:150,opacity:.5};E.validate(JSON.parse(JSON.stringify(p)));
assert.throws(()=>E.validate({...p,controls:{...p.controls,heal:['KeyZ']}}));assert.throws(()=>E.validate({...p,controls:{heal:['KeyZ']}}));assert.throws(()=>E.validate({...p,soundBindings:{heal:'missing'}}));assert.throws(()=>E.validate({...p,assets:[{...a,frameDurations:[.1]}]}));assert.throws(()=>E.validate({...p,maps:[{...p.maps[0],backgroundAdjust:{...p.maps[0].backgroundAdjust,scale:Infinity}}]}));
assert.deepEqual(E.backgroundRect({},100,100,200,100,{fit:'contain',x:10,y:0,scale:200,opacity:.5}),{x:20,y:-50,w:200,h:200,opacity:.5});
s=E.createState(p);s.queue=[{type:'sound',sound:'sfx'},{type:'text',text:'after sound'}];E.next(p,s);assert.deepEqual(s.audioEvents,['sfx']);assert.equal(s.dialog.text,'after sound');E.validate(E.sample());
console.log('PASS: healing cast/completion/cap/interruption/capture, GIF timings, background transform, keys/conflicts, WAV references and event queue, save roundtrip/legacy');

p.sounds[0].loop=true;E.validate(p);assert.throws(()=>E.validate({...p,sounds:[{...p.sounds[0],loop:'yes'}]}));s=E.createState(p);s.queue=[{type:'sound',sound:'sfx',stop:true}];E.next(p,s);assert.deepEqual(s.audioEvents,[{id:'sfx',stop:true}]);
const legacy=A.sample();legacy.controls={heal:['KeyS']};assert.deepEqual(E.controls(legacy).prone,['ArrowDown']);E.validate(legacy);legacy.controls={heal:['KeyS'],attack:['ArrowDown']};assert.equal(E.controls(legacy).prone.length,1);assert(!['KeyS','ArrowDown'].includes(E.controls(legacy).prone[0]));E.validate(legacy);
