const {chromium}=require(process.env.PLAYWRIGHT_MODULE||(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES?process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright':'playwright'));
const spart=process.env.CHROMIUM_PATH?{executablePath:async()=>process.env.CHROMIUM_PATH,args:['--no-sandbox']}:require('@sparticuz/chromium').default;
const fs=require('fs'),assert=require('assert/strict'),path=require('path');
(async()=>{const browser=await chromium.launch({executablePath:await spart.executablePath(),args:spart.args,headless:true});const page=await browser.newPage({viewport:{width:1500,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('file://'+path.resolve('app/index.html'));await page.waitForSelector('#mapCanvas');await page.evaluate(()=>document.fonts.ready);
 await page.screenshot({path:'editor-preview.png'});
 assert.equal(await page.locator('#mapTitle').textContent(),'솔바람 마을');
 await page.locator('[data-asset="stone"]').click();const box=await page.locator('#mapCanvas').boundingBox();await page.mouse.click(box.x+3*32+16,box.y+3*32+16);assert.equal(await page.evaluate(()=>P.maps[0].ground[3*24+3]),'stone');await page.locator('#undo').click();assert.equal(await page.evaluate(()=>P.maps[0].ground[3*24+3]),'grass');await page.locator('#redo').click();assert.equal(await page.evaluate(()=>P.maps[0].ground[3*24+3]),'stone');
 await page.locator('[data-event="guide"]').click();await page.locator('[data-ev="name"]').fill('도움 안내인');await page.locator('[data-ev="name"]').blur();assert.equal(await page.evaluate(()=>P.maps[0].events[0].name),'도움 안내인');await page.locator('[data-add="switch"]').click();assert.equal(await page.locator('.command').count(),3);
 await page.locator('#play').click();await page.evaluate(()=>{playState.x=4;playState.y=11;playState.dir=3;paintPlay()});await page.keyboard.press('Enter');assert.match(await page.locator('#dialogue').textContent(),/열쇠/);await page.keyboard.press('Enter');await page.locator('#inventory').click();assert.match(await page.locator('#bag').textContent(),/오래된 열쇠/);await page.locator('#inventory').click();await page.evaluate(()=>{playState.x=6;playState.y=8;E.move(P,playState,0,-1);paintPlay()});assert.equal(await page.locator('#playMapName').textContent(),'작은 집');await page.screenshot({path:'play-preview.png'});await page.locator('#stopPlay').click();
 // Import a real 64x32 PNG split into two tiles, persist and load the data again.
 const data=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=64;c.height=32;const x=c.getContext('2d');x.fillStyle='#ee6666';x.fillRect(0,0,32,32);x.fillStyle='#6699ee';x.fillRect(32,0,32,32);return c.toDataURL().split(',')[1]});fs.writeFileSync('tests/import.png',Buffer.from(data,'base64'));await page.locator('#assetFile').setInputFiles('tests/import.png');await page.waitForSelector('#addAsset');await page.locator('#addAsset').click();assert.equal(await page.evaluate(()=>P.assets.length),2);assert.match(await page.evaluate(()=>P.assets[0].data),/^data:image\/png/);
 const project=await page.evaluate(()=>JSON.stringify(P));await page.evaluate(t=>loadText(t),project);assert.equal(await page.evaluate(()=>P.assets.length),2);
 // Native bridge stub tests save and export wiring without pretending to test Windows dialogs.
 await page.evaluate(()=>{window.desktop={save:async text=>{window.saved=text;return 'project.storyforge'},export:async text=>{window.exported=text;return 'game.html'},autosave:async()=>{},reset:async()=>{}}});await page.locator('#saveProject').click();assert.equal(await page.evaluate(()=>JSON.parse(window.saved).name),'솔바람 마을의 작은 열쇠');await page.locator('#exportGame').click();const html=await page.evaluate(()=>window.exported);assert(html.includes('StoryEngineFactory'));fs.writeFileSync('sample-game.html',html);
 const game=await browser.newPage({viewport:{width:1200,height:850}});game.on('pageerror',e=>errors.push(e.message));await game.goto('file://'+path.resolve('sample-game.html'));await game.waitForSelector('#game');assert.match(await game.locator('#title').textContent(),/솔바람/);const pos1=await game.locator('#game').getAttribute('style');await game.keyboard.press('ArrowLeft');await game.locator('#inventory').click();assert.equal(await game.locator('#bag').isVisible(),true);await game.screenshot({path:'export-preview.png'});
 await page.setViewportSize({width:1000,height:720});await page.screenshot({path:'editor-small-preview.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 assert.deepEqual(errors,[]);console.log('PASS: UI paint / undo / redo, event editor, play dialogue and inventory, map travel, PNG tile import, project roundtrip, save/export bridge, standalone game, 1000px layout.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
