'use strict';
function ActionFactory(E) {
 const states=['idle','run','jump','fall','attack','hurt','grabbed','grab','healCast','heal'];
 const defaults=()=>({width:40,height:96,bodyWidth:24,bodyHeight:76,heads:4,speed:180,jump:510,gravity:1400,hp:5,damage:1,healCastTime:1,healAmount:2,clips:{}});
 const config=p=>({...defaults(),...p.action,clips:p.action?.clips||{}});
 const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
 function map(name='횡스크롤 스테이지',w=60,h=18){const m=E.makeMap(name,w,h);m.ground.fill('air');m.enemies=[];for(let y=h-2;y<h;y++)for(let x=0;x<w;x++){m.ground[y*w+x]='stone';m.collision[y*w+x]=true;}return m;}
 function enemy(x=12,y=15){return {id:'n'+Math.random().toString(36).slice(2,9),name:'경비병',x,y,hp:3,speed:65,range:180,patrol:100,damage:1,canGrab:true,hold:3,escape:6,offsetX:26,offsetY:0,width:44,height:96,clips:{}};}
 function sample(){const m=map('바람 절벽');m.id='cliff';for(let x=14;x<20;x++){m.ground[12*m.w+x]='stone';m.collision[12*m.w+x]=true;}for(let x=27;x<33;x++){m.ground[10*m.w+x]='stone';m.collision[10*m.w+x]=true;}m.enemies=[enemy(10,15),enemy(24,15)];m.events=[{id:'sign',name:'길 안내',x:4,y:15,appearance:'chest',trigger:'action',solid:false,condition:{type:'none'},commands:[{type:'text',speaker:'안내판',text:'방향키로 이동 · Space로 점프 · Z로 공격\n적에게 잡히면 X를 여러 번 눌러 탈출하세요.'}]}];return {format:'story-forge',version:1,mode:'action',name:'바람 절벽의 모험',maps:[m],assets:[],start:{map:m.id,x:3,y:15,sprite:'hero'},action:defaults(),effects:[]};}
 function validate(p){const fail=s=>{throw Error('액션/연출 설정: '+s)},num=(v,a,b,label)=>{if(!Number.isFinite(v)||v<a||v>b)fail(label)},clips=c=>{if(!c||typeof c!=='object'||Array.isArray(c))fail('동작 목록');for(const [k,v] of Object.entries(c))if(!states.includes(k)||v&&!p.assets.some(a=>a.id===v&&['animation','character'].includes(a.kind)))fail('동작 그림 참조');};
 if(p.mode!==undefined&&!['topdown','action'].includes(p.mode))fail('게임 모드');
 for(const a of p.assets)if(a.kind==='animation'){for(const key of ['cols','rows','frames'])if(!Number.isInteger(a[key]))fail('시트 정수 규격');num(a.cols,1,32,'가로 프레임');num(a.rows,1,32,'세로 프레임');num(a.frames,1,Math.min(256,a.cols*a.rows),'프레임 수');num(a.fps,1,60,'재생 속도');}
 if(p.action){const c=config(p);for(const k of ['width','height','bodyWidth','bodyHeight'])num(c[k],8,256,k);num(c.heads,3,5,'등신');num(c.speed,20,600,'이동 속도');num(c.jump,100,1000,'점프');num(c.gravity,200,3000,'중력');num(c.hp,1,999,'체력');num(c.damage,1,99,'공격력');num(c.healCastTime,.1,10,'회복 시전 시간');num(c.healAmount,1,999,'회복량');clips(c.clips);}
 for(const m of p.maps){if(m.enemies!==undefined&&!Array.isArray(m.enemies))fail('적 목록');if((m.enemies||[]).length>100)fail('적은 맵당 100개까지');const ids=new Set();for(const n of m.enemies||[]){if(typeof n.id!=='string'||ids.has(n.id))fail('적 ID');ids.add(n.id);num(n.x,0,m.w-1,'적 X');num(n.y,0,m.h-1,'적 Y');for(const k of ['x','y','hp','escape'])if(!Number.isInteger(n[k]))fail('적 정수 설정');num(n.hp,1,999,'적 체력');num(n.speed,0,400,'적 속도');num(n.range,0,1500,'감지 거리');num(n.patrol,0,1500,'순찰 거리');num(n.damage,0,99,'적 피해');num(n.hold,.2,30,'잡기 시간');num(n.escape,1,50,'탈출 횟수');num(n.offsetX,-160,160,'잡기 X');num(n.offsetY,-160,160,'잡기 Y');num(n.width,8,256,'적 너비');num(n.height,8,256,'적 높이');clips(n.clips);}}
 if(p.effects!==undefined&&!Array.isArray(p.effects))fail('화면 연출 목록');if((p.effects||[]).length>50)fail('화면 연출은 50개까지');const ids=new Set();for(const f of p.effects||[]){if(typeof f.id!=='string'||ids.has(f.id))fail('연출 ID');ids.add(f.id);if(!p.assets.some(a=>a.id===f.asset))fail('연출 그림');if(!['always','grabbed','hurt','attack','airborne','hp','switch','item','healCast','heal'].includes(f.when))fail('연출 조건');if(f.map&&!p.maps.some(m=>m.id===f.map))fail('연출 맵');for(const k of ['x','y'])num(f[k],-100,100,k);for(const k of ['width','height'])num(f[k],1,200,k);num(f.opacity,0,1,'투명도');num(f.duration,0,120,'표시 시간');num(f.threshold,0,999,'조건 수치');if(typeof f.loop!=='boolean')fail('반복 재생');}return p;}
 const originalValidate=E.validate;E.validate=p=>validate(originalValidate(p));
 function create(p){const s=E.createState(p),c=config(p);Object.assign(s,{px:(s.x+.5)*32,py:(s.y+1)*32,vx:0,vy:0,facing:1,grounded:false,hp:c.hp,anim:'idle',time:0,attack:0,attackId:0,healCast:0,healing:0,hurt:0,invincible:0,grab:null,dead:false,enemyMaps:{},effectState:{}});enter(p,s);return s;}
 function enter(p,s){if(s.loadedMap===s.map)return;const m=p.maps.find(m=>m.id===s.map);s.px=(s.x+.5)*32;s.py=(s.y+1)*32;s.vx=s.vy=0;s.healCast=0;s.healing=0;s.grab=null;s.loadedMap=s.map;s.touchId=null;if(!s.enemyMaps[s.map])s.enemyMaps[s.map]=(m.enemies||[]).map(n=>({...E.clone(n),px:(n.x+.5)*32,py:(n.y+1)*32,origin:(n.x+.5)*32,vy:0,facing:-1,cooldown:0,hurt:0,hit:0,anim:'idle'}));}
 function box(b,w,h){return {left:b.px-w/2,right:b.px+w/2,top:b.py-h,bottom:b.py};}
 function overlap(a,b){return a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top;}
 function blocked(p,m,b,w,h){const r=box(b,w,h);for(let y=Math.floor(r.top/32);y<=Math.floor((r.bottom-.01)/32);y++)for(let x=Math.floor(r.left/32);x<=Math.floor((r.right-.01)/32);x++){if(y>=m.h)continue;if(y<0||x<0||x>=m.w||E.solid(p,m,x,y)||m.events.some(e=>e.solid&&e.x===x&&e.y===y))return true;}return false;}
 function travel(p,m,b,dx,dy,w,h){const steps=Math.max(1,Math.ceil(Math.max(Math.abs(dx),Math.abs(dy))/4));b.grounded=false;for(let i=0;i<steps;i++){b.px+=dx/steps;if(blocked(p,m,b,w,h))b.px-=dx/steps;b.py+=dy/steps;if(blocked(p,m,b,w,h)){b.py-=dy/steps;if(dy>0)b.grounded=true;b.vy=0;}}}
 function release(s){if(!s.grab)return;const n=(s.enemyMaps[s.map]||[]).find(n=>n.id===s.grab.id);if(n){n.cooldown=2;n.anim='idle';}s.grab=null;s.invincible=1;s.anim='idle';}
 function hit(s,damage){if(s.invincible>0||s.dead)return;s.hp=Math.max(0,s.hp-damage);s.healCast=0;s.healing=0;s.hurt=.35;s.invincible=1;s.anim='hurt';if(!s.hp){release(s);s.dead=true;s.anim='hurt';}}
 function tick(p,s,dt,input={}){dt=clamp(dt,0,1/30);enter(p,s);if(s.dialog||input.paused||s.dead)return;s.time+=dt;const m=p.maps.find(m=>m.id===s.map),c=config(p),enemies=s.enemyMaps[s.map];s.hurt=Math.max(0,s.hurt-dt);s.invincible=Math.max(0,s.invincible-dt);s.attack=Math.max(0,s.attack-dt);s.healing=Math.max(0,s.healing-dt);for(const n of enemies){n.cooldown=Math.max(0,n.cooldown-dt);n.hurt=Math.max(0,n.hurt-dt);}
 if(s.grab){s.grab.time-=dt;if(input.escape)s.grab.presses++;if(s.grab.time<=0||s.grab.presses>=s.grab.required)release(s);else{s.anim='grabbed';return;}}
 if(s.healCast>0){s.healCast=Math.max(0,s.healCast-dt);if(s.healCast===0){s.hp=Math.min(c.hp,s.hp+c.healAmount);s.healing=.45;}}
 if(input.heal&&s.hp<c.hp&&s.grounded&&!s.hurt&&!s.attack&&!s.healCast&&!s.healing)s.healCast=c.healCastTime;
 const casting=s.healCast>0||s.healing>0;
 if(!casting&&input.attack&&s.attack===0){s.attack=.28;s.attackId++;}const direction=casting?0:(input.right?1:0)-(input.left?1:0);if(direction)s.facing=direction;s.vx=direction*c.speed*(s.attack>0?.45:1);if(!casting&&input.jump&&s.grounded){s.vy=-c.jump;s.grounded=false;}s.vy=Math.min(900,s.vy+c.gravity*dt);travel(p,m,s,s.vx*dt,s.vy*dt,c.bodyWidth,c.bodyHeight);s.x=clamp(Math.floor(s.px/32),0,m.w-1);s.y=clamp(Math.floor((s.py-1)/32),0,m.h-1);s.dir=s.facing>0?2:1;s.anim=s.hurt?'hurt':s.healCast?'healCast':s.healing?'heal':s.attack?'attack':!s.grounded?(s.vy<0?'jump':'fall'):direction?'run':'idle';
 if(s.py>m.h*32+180){s.hp=0;s.dead=true;s.anim='hurt';return;}
 const playerBox=box(s,c.bodyWidth,c.bodyHeight);for(const n of enemies){if(n.hp<=0)continue;const w=Math.min(n.width*.6,40),h=n.height*.8;const reach={left:s.facing>0?s.px:s.px-c.bodyWidth/2-48,right:s.facing>0?s.px+c.bodyWidth/2+48:s.px,top:s.py-c.bodyHeight,bottom:s.py};if(s.attack>0&&n.hit!==s.attackId&&overlap(reach,box(n,w,h))){n.hp=Math.max(0,n.hp-c.damage);n.hit=s.attackId;n.hurt=.3;n.cooldown=.8;if(n.hp<=0)continue;}
 const dist=s.px-n.px;let dir=0;if(Math.abs(dist)<n.range)dir=Math.sign(dist);else if(n.patrol>0){dir=n.facing;if(n.px>n.origin+n.patrol)dir=-1;if(n.px<n.origin-n.patrol)dir=1;}if(dir)n.facing=dir;n.vy=Math.min(900,n.vy+c.gravity*dt);const before=n.px;travel(p,m,n,n.hurt?0:dir*n.speed*dt,n.vy*dt,w,h);if(Math.abs(n.px-before)<.01&&dir)n.facing=-dir;n.anim=n.hurt?'hurt':dir?'run':'idle';if(n.py>m.h*32+160){n.hp=0;continue;}
 if(overlap(playerBox,box(n,w,h))&&n.cooldown===0&&s.invincible===0){hit(s,n.damage);n.cooldown=1.2;if(n.canGrab&&!s.dead){s.grab={id:n.id,time:n.hold,required:n.escape,presses:0};s.anim='grabbed';n.anim='grab';const candidate={px:n.px+n.offsetX*n.facing,py:n.py+n.offsetY};if(!blocked(p,m,candidate,c.bodyWidth,c.bodyHeight)){s.px=candidate.px;s.py=candidate.py;}s.vx=s.vy=0;break;}}}
 const e=m.events.find(e=>e.trigger==='touch'&&overlap(box(s,c.bodyWidth,c.bodyHeight),{left:e.x*32,right:(e.x+1)*32,top:e.y*32,bottom:(e.y+1)*32}));if(e){if(s.touchId!==e.id){s.touchId=e.id;E.trigger(p,s,e);enter(p,s);}}else s.touchId=null;
 if(input.interact&&!casting){const e=m.events.find(e=>e.trigger==='action'&&Math.abs((e.x+.5)*32-s.px)<72&&Math.abs((e.y+1)*32-s.py)<96);if(e)E.trigger(p,s,e);enter(p,s);}}
 const cache=new Map();function image(a){let im=cache.get(a.id);if(!im||im.src!==a.data){im=new Image();im.src=a.data;cache.set(a.id,im);}return im;}
 function frame(ctx,p,id,x,y,w,h,time,loop=true,flip=false,anchorY=.5){const a=p.assets.find(a=>a.id===id);if(!a)return false;const im=image(a);if(!im.complete||!im.naturalWidth)return true;const cols=a.cols||1,rows=a.rows||1,i=E.frameIndex(a,time,loop),sw=im.naturalWidth/cols,sh=im.naturalHeight/rows;const r=E.fitRect(sw,sh,x,y,w,h,a.preserveAspect,anchorY);x=r.x;y=r.y;w=r.w;h=r.h;ctx.save();ctx.translate(x+(flip?w:0),y);if(flip)ctx.scale(-1,1);ctx.drawImage(im,i%cols*sw,Math.floor(i/cols)*sh,sw,sh,0,0,w,h);ctx.restore();return true;}
 function actor(ctx,p,b,c,time,enemy=false){if(b.visualAnim!==b.anim){b.visualAnim=b.anim;b.visualStart=time;}const clipTime=time-(b.visualStart||0);ctx.save();ctx.translate(b.px,b.py);const id=c.clips?.[b.anim]||c.clips?.idle;if(!frame(ctx,p,id,-c.width/2,-c.height,c.width,c.height,clipTime,!['attack','hurt','jump','fall','heal'].includes(b.anim),b.facing<0,1)){
 const head=c.height/(c.heads||4),stride=b.anim==='run'?Math.sin(time*15)*head*.32:0;ctx.scale(b.facing||1,1);ctx.fillStyle=enemy?'#ed9a78':'#a89aff';ctx.fillRect(-c.width*.26,-c.height+head,c.width*.52,c.height*.44);ctx.fillStyle='#f3cfad';ctx.fillRect(-head*.4,-c.height,head*.8,head*.85);ctx.fillStyle=enemy?'#61413e':'#403855';ctx.fillRect(-head*.45,-c.height,head*.9,head*.22);ctx.fillStyle='#dddbea';ctx.fillRect(-c.width*.25+stride,-c.height*.34,c.width*.19,c.height*.34);ctx.fillRect(c.width*.08-stride,-c.height*.34,c.width*.19,c.height*.34);ctx.fillStyle='#f3cfad';const arm=b.anim==='attack'?c.width*.85:b.anim==='grabbed'?-c.width*.6:c.width*.4;ctx.fillRect(0,-c.height*.68,arm,head*.25);ctx.fillStyle='#30283a';ctx.fillRect(head*.15,-c.height+head*.36,3,3);}
 if(['healCast','heal'].includes(b.anim)){ctx.strokeStyle=b.anim==='heal'?'#a6ffb7':'#79c9df';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,-c.height*.5,c.width*.7+(b.anim==='heal'?8:Math.sin(time*8)*3),0,Math.PI*2);ctx.stroke();}if(b.anim==='attack'){ctx.strokeStyle='#fff3b2';ctx.lineWidth=5;ctx.beginPath();ctx.arc(b.facing*18,-c.height*.48,38,-1.1,1.1);ctx.stroke();}ctx.restore();}
 function draw(ctx,p,s,w,h){const m=p.maps.find(m=>m.id===s.map),c=config(p);ctx.clearRect(0,0,w,h);const sky=ctx.createLinearGradient(0,0,0,h);sky.addColorStop(0,'#26354f');sky.addColorStop(1,'#647f91');ctx.fillStyle=sky;ctx.fillRect(0,0,w,h);const camX=clamp(s.px-w*.4,0,Math.max(0,m.w*32-w)),camY=m.h*32<h?m.h*32-h:clamp(s.py-h*.72,0,m.h*32-h);const bg=p.assets.find(a=>a.id===m.background);if(bg&&m.backgroundSpace!=='map')E.drawBackground(ctx,p,m,w,h,s.time);ctx.save();ctx.translate(-camX,-camY);if(bg&&m.backgroundSpace==='map')E.drawBackground(ctx,p,m,m.w*32,m.h*32,s.time);const x0=Math.max(0,Math.floor(camX/32)),x1=Math.min(m.w,Math.ceil((camX+w)/32)+1),y0=Math.max(0,Math.floor(camY/32)),y1=Math.min(m.h,Math.ceil((camY+h)/32)+1);for(let y=y0;y<y1;y++)for(let x=x0;x<x1;x++){const i=y*m.w+x;E.drawAsset(ctx,p,m.ground[i],x*32,y*32,32,0,0,s.time);E.drawAsset(ctx,p,m.objects[i],x*32,y*32,32,0,0,s.time);}for(const e of m.events)E.drawAsset(ctx,p,e.appearance,e.x*32,e.y*32,32,0,0,s.time);for(const n of s.enemyMaps[s.map]||[])if(n.hp>0){actor(ctx,p,n,n,s.time,true);ctx.fillStyle='#171c28';ctx.fillRect(n.px-20,n.py-n.height-9,40,4);ctx.fillStyle='#f5b283';ctx.fillRect(n.px-20,n.py-n.height-9,40*n.hp/(m.enemies.find(e=>e.id===n.id)?.hp||n.hp),4);}actor(ctx,p,s,c,s.time);ctx.restore();}
 function condition(f,p,s){if(f.map&&f.map!==s.map)return false;switch(f.when){case 'always':return true;case 'healCast':return s.healCast>0;case 'heal':return s.healing>0;case 'grabbed':return !!s.grab;case 'hurt':return s.hurt>0;case 'attack':return s.attack>0;case 'airborne':return p.mode==='action'&&!s.grounded;case 'hp':return p.mode==='action'&&s.hp<=f.threshold;case 'switch':return !!s.switches[f.key];case 'item':return (s.inventory[f.key]||0)>=Math.max(1,f.threshold);default:return false;}}
 function effects(ctx,p,s,w,h,dt){s.effectState??={};for(const f of p.effects||[]){const on=condition(f,p,s),r=s.effectState[f.id]??={time:0,on:false};if(on&&!r.on)r.time=0;r.on=on;if(!on)continue;r.time+=dt;if(f.duration&&r.time>f.duration)continue;ctx.save();ctx.globalAlpha=f.opacity;frame(ctx,p,f.asset,w*f.x/100,h*f.y/100,w*f.width/100,h*f.height/100,r.time,f.loop);ctx.restore();}}
 return {states,defaults,config,map,enemy,sample,validate,create,tick,enter,blocked,box,overlap,frame,actor,draw,effects,condition,release};
}
if(typeof module!=='undefined')module.exports=ActionFactory;else window.Action=ActionFactory(window.Engine);
