'use strict';
const A=window.Action;
const motionNames={idle:'대기',run:'이동',jump:'점프',fall:'낙하',attack:'공격',hurt:'피격',grabbed:'잡힌 상태',grab:'적의 잡기',healCast:'회복 시전 중',heal:'회복될 때',prone:'엎드리기'};
const conditionNames={prone:'엎드린 동안',healCast:'회복 시전 중',heal:'회복될 때',prone:'엎드리기',always:'항상 표시',grabbed:'적에게 잡혔을 때',hurt:'피격 중',attack:'공격 중',airborne:'공중에 있을 때',hp:'체력이 지정 값 이하',switch:'스위치가 켜졌을 때',item:'아이템을 지정 수량 이상 보유'};
const numberField=(label,key,v,min,max,step=1)=>field(label,inp(v,`type="number" min="${min}" max="${max}" step="${step}" data-config="${key}"`));
function imageOptions(v){return opt('','기본 그림',v)+P.assets.filter(a=>['character','animation'].includes(a.kind)).map(a=>opt(a.id,a.name,v)).join('');}
function clipFields(c){return `<div class="clipGrid">${A.states.map(k=>field(motionNames[k],sel(imageOptions(c[k]||''),`data-clip="${k}"`))).join('')}</div>`;}
function readConfig(c){$('modalContent').querySelectorAll('[data-config]').forEach(n=>c[n.dataset.config]=n.type==='checkbox'?n.checked:Number(n.value));$('modalContent').querySelectorAll('[data-clip]').forEach(n=>c.clips[n.dataset.clip]=n.value);return c;}
function wideModal(html,setup){modal(html,setup);$('modal').classList.add('wideModal');}
$('modal').addEventListener('close',()=>$('modal').classList.remove('wideModal'));
const modePanel=document.createElement('section');modePanel.className='modePanel';modePanel.innerHTML=`${field('게임 모드',sel(opt('topdown','탑다운 RPG','topdown')+opt('action','횡스크롤 액션','topdown'),'id="gameMode"'))}<div class="row"><button id="actorSettings">캐릭터 동작</button><button id="screenEffects">화면 연출</button></div><button class="quiet wide" id="motionImport">＋ 동작 / 연출 그림 불러오기</button><button class="quiet wide" id="actionExample">횡스크롤 예제 열기</button><div class="editorModeHint" id="modeHint"></div><div id="enemyList"></div>`;document.querySelector('.left').prepend(modePanel);
const enemyButton=document.createElement('button');enemyButton.dataset.tool='enemy';enemyButton.textContent='적 배치';$('tools').append(enemyButton);enemyButton.onclick=()=>setTool('enemy');
function syncMode(){const action=P.mode==='action';$('gameMode').value=action?'action':'topdown';enemyButton.hidden=!action;$('actorSettings').disabled=!action;$('modeHint').textContent=action?'시작 위치와 적 위치는 발이 닿는 칸입니다. 빈 공간을 그리고, ‘투명 충돌 타일’로 바닥·벽을 만드세요. 플레이에서는 보이지 않습니다.':'기존 RPG 프로젝트는 그대로 사용할 수 있어요.';$('enemyList').innerHTML=action?`<div class="sectionTitle">이 맵의 적 <span>${(map().enemies||[]).length}</span></div>${(map().enemies||[]).map(n=>`<button class="eventItem" data-enemy="${esc(n.id)}">${esc(n.name)} <small>${n.x}, ${n.y} · HP ${n.hp}</small></button>`).join('')}`:'';$('enemyList').querySelectorAll('[data-enemy]').forEach(b=>b.onclick=()=>enemyModal(map().enemies.find(n=>n.id===b.dataset.enemy)));}
const baseRender=render;render=function(){baseRender();syncMode();};
const baseSetTool=setTool;setTool=function(t){baseSetTool(t);if(t==='enemy')$('toolHint').textContent='빈 칸 클릭: 적 추가 · 기존 적 클릭: 잡기와 동작 설정';};
const baseDraw=draw;draw=function(){baseDraw();if(P.mode!=='action')return;const ctx=$('mapCanvas').getContext('2d'),scale=Number($('zoom').value);ctx.save();ctx.scale(scale,scale);if(P.start.map===mapId)A.actor(ctx,P,{px:(P.start.x+.5)*32,py:(P.start.y+1)*32,anim:'idle',visualAnim:'idle',visualStart:0,facing:1},A.config(P),performance.now()/1000);for(const n of map().enemies||[]){A.actor(ctx,P,{...n,px:(n.x+.5)*32,py:(n.y+1)*32,anim:'idle',visualAnim:'idle',visualStart:0,facing:-1},n,performance.now()/1000,true);ctx.strokeStyle='#f09d81';ctx.strokeRect(n.x*32,n.y*32,32,32);ctx.fillStyle='#ffe2b9';ctx.font='11px sans-serif';ctx.fillText(n.name,n.x*32-10,(n.y+1)*32-n.height-5);}ctx.restore();};
const baseEdit=editCell;editCell=function(x,y){if(tool!=='enemy')return baseEdit(x,y);if(x<0||y<0||x>=map().w||y>=map().h)return;stroke=false;const n=(map().enemies||[]).find(n=>n.x===x&&n.y===y);enemyModal(n||A.enemy(x,y),!n);};
$('gameMode').onchange=()=>{const nextMode=$('gameMode').value;confirmBox('게임 모드를 바꿀까요?',nextMode==='action'?'현재 맵과 이벤트는 보존됩니다. 횡스크롤에서는 중력이 적용됩니다. 발판의 통행을 막고, 캐릭터 키만큼 빈 공간을 확보해 주세요.':'맵과 에셋은 보존됩니다. 적과 액션 동작은 횡스크롤 모드에서만 동작합니다.',()=>{checkpoint();P.mode=nextMode;delete P.controls;if(nextMode==='action')P.action??=A.defaults();setTool('brush');changed();render();});$('modal').addEventListener('close',syncMode,{once:true});};
$('actionExample').onclick=()=>confirmBox('횡스크롤 예제를 열까요?','저장하지 않은 변경은 사라집니다. 현재 프로젝트를 먼저 저장하세요.',async()=>{P=A.sample();await window.desktop?.reset();mapId=P.start.map;eventId=null;history=[];future=[];setTool('brush');changed();render();});
$('actorSettings').onclick=()=>{const c=E.clone(A.config(P));wideModal(`<h2>횡스크롤 캐릭터</h2><p>발 위치를 기준으로 그림을 정렬합니다. 등신은 기본 캐릭터에 적용되고, 내 그림은 지정한 너비·높이 영역에 표시됩니다. 에셋의 ‘원본 비율 유지’를 켜면 발 위치를 고정하고 늘어짐 없이 맞춥니다. 오른쪽을 보는 그림을 넣으면 왼쪽 이동 시 자동 반전됩니다.</p><div class="configGrid">${numberField('기본 캐릭터 등신','heads',c.heads,3,5)}${numberField('그림 너비 px','width',c.width,8,256)}${numberField('그림 높이 px','height',c.height,8,256)}${numberField('충돌 너비 px','bodyWidth',c.bodyWidth,8,256)}${numberField('충돌 높이 px','bodyHeight',c.bodyHeight,8,256)}${numberField('이동 속도 px/초','speed',c.speed,20,600)}${numberField('점프 힘','jump',c.jump,100,1000)}${numberField('중력','gravity',c.gravity,200,3000)}${numberField('최대 체력','hp',c.hp,1,999)}${numberField('공격 피해','damage',c.damage,1,99)}${numberField('회복 시전 시간 (초)','healCastTime',c.healCastTime,.1,10,.1)}${numberField('회복량','healAmount',c.healAmount,1,999)}</div><h3>상태별 동작 그림</h3><p class="actionHelp">동작 / 연출 그림에서 프레임 시트를 불러온 뒤 연결하세요. 빈 동작은 대기 그림 또는 기본 캐릭터로 표시됩니다.</p>${clipFields(c.clips)}<div class="actions"><button data-close>취소</button><button class="primary" id="applyActor">적용</button></div>`,()=>{$('applyActor').onclick=()=>{try{readConfig(c);A.validate({...P,action:c});checkpoint();P.action=c;changed();$('modal').close();draw();}catch(e){toast(e.message);}};});};
function enemyModal(original,isNew=false){const n=E.clone(original);wideModal(`<h2>${isNew?'적 추가':'적 설정'}</h2>${field('적 이름',inp(n.name,'id="enemyName" maxlength="60"'))}<div class="configGrid">${numberField('발 위치 X 칸','x',n.x,0,map().w-1)}${numberField('발 위치 Y 칸','y',n.y,0,map().h-1)}${numberField('체력','hp',n.hp,1,999)}${numberField('이동 속도','speed',n.speed,0,400)}${numberField('감지 거리 px','range',n.range,0,1500)}${numberField('순찰 반경 px','patrol',n.patrol,0,1500)}${numberField('접촉 피해','damage',n.damage,0,99)}${numberField('그림 너비 px','width',n.width,8,256)}${numberField('그림 높이 px','height',n.height,8,256)}</div><h3>잡기와 탈출</h3><label class="check"><input type="checkbox" data-config="canGrab" ${n.canGrab?'checked':''}> 엎드린 주인공과 닿으면 붙잡기</label><div class="configGrid">${numberField('최대 잡기 시간 초','hold',n.hold,.2,30,.1)}${numberField('탈출 입력 횟수','escape',n.escape,1,50)}${numberField('잡힌 캐릭터 X 간격 px','offsetX',n.offsetX,-160,160)}${numberField('잡힌 캐릭터 Y 간격 px','offsetY',n.offsetY,-160,160)}</div><p class="actionHelp">서 있거나 이동 중인 주인공에게는 접촉 피해를 줍니다. 엎드린 주인공은 피해 대신 붙잡습니다. 잡힘 중에는 이동·점프·공격이 멈춥니다. 시간 만료 또는 X 연타로 풀립니다. X 간격은 적의 시선 방향 기준이며 벽과 겹치는 배치는 적용하지 않습니다. 주인공의 ‘잡힌 상태’와 적의 ‘적의 잡기’ 그림이 함께 재생됩니다.</p>${clipFields(n.clips)}<div class="actions">${!isNew?'<button class="danger" id="removeEnemy">삭제</button>':''}<button data-close>취소</button><button class="primary" id="applyEnemy">적용</button></div>`,()=>{$('applyEnemy').onclick=()=>{try{readConfig(n);n.name=$('enemyName').value.trim()||'적';const list=isNew?[...(map().enemies||[]),n]:map().enemies.map(e=>e.id===n.id?n:e);A.validate({...P,maps:P.maps.map(m=>m.id===mapId?{...m,enemies:list}:m)});checkpoint();map().enemies=list;changed();$('modal').close();render();}catch(e){toast(e.message);}};if($('removeEnemy'))$('removeEnemy').onclick=()=>{checkpoint();map().enemies=map().enemies.filter(e=>e.id!==n.id);changed();$('modal').close();render();};});}
const motionFile=document.createElement('input');motionFile.type='file';motionFile.accept='image/png,image/jpeg,image/webp';motionFile.hidden=true;motionFile.id='motionFile';document.body.append(motionFile);$('motionImport').onclick=()=>motionFile.click();motionFile.onchange=async()=>{const file=motionFile.files[0];motionFile.value='';if(!file)return;try{if(file.size>12*1024*1024)throw Error('그림은 12MB 이하로 넣어주세요.');const im=new Image(),url=URL.createObjectURL(file);try{im.src=url;await im.decode();}finally{URL.revokeObjectURL(url);}if(im.naturalWidth>4096||im.naturalHeight>4096)throw Error('가로·세로 4096px 이하만 지원합니다.');const canvas=document.createElement('canvas');canvas.width=im.naturalWidth;canvas.height=im.naturalHeight;canvas.getContext('2d').drawImage(im,0,0);const data=canvas.toDataURL('image/png');modal(`<h2>동작 / 연출 그림</h2><p>정지 그림은 1×1로, 애니메이션은 같은 크기의 칸을 나열한 PNG·WebP 시트로 넣으세요. 왼쪽에서 오른쪽, 위에서 아래 순서로 재생됩니다.</p><label class="check"><input type="checkbox" id="motionAspect" checked> 원본 비율 유지 (프레임 한 칸 기준)</label><img class="sheetPreview" src="${data}" alt="불러올 시트">${field('그림 이름',inp(file.name.replace(/\.[^.]+$/,''),'id="motionName" maxlength="60"'))}<div class="configGrid">${numberField('가로 칸','cols',1,1,32)}${numberField('세로 칸','rows',1,1,32)}${numberField('실제 프레임 수','frames',1,1,256)}${numberField('초당 프레임','fps',8,1,60)}</div><div class="actions"><button data-close>취소</button><button id="addMotion" class="primary">불러오기</button></div>`,()=>{$('addMotion').onclick=()=>{try{const a={id:uid('motion'),name:$('motionName').value.trim()||'동작 그림',kind:'animation',data,preserveAspect:$('motionAspect').checked};readConfig(a);if(im.naturalWidth%a.cols||im.naturalHeight%a.rows)throw Error('이미지 크기가 가로·세로 칸 수로 정확히 나뉘어야 합니다.');const next={...P,assets:[...P.assets,a]};E.validate(next);if(JSON.stringify(next).length>60*1024*1024)throw Error('프로젝트는 60MB 이내로 유지해 주세요.');checkpoint();P.assets.push(a);changed();$('modal').close();tab='other';selected=a.id;render();toast('그림을 등록했어요. 캐릭터 동작 또는 화면 연출에서 연결하세요.');}catch(e){toast(e.message);}};});}catch(e){toast(e.message);}};
$('screenEffects').onclick=()=>effectsModal();
function effectsModal(){if(!P.assets.length)return toast('먼저 동작 / 연출 그림을 불러오세요.');let list=E.clone(P.effects||[]),current=list[0]?.id,previewRAF=0,previewStart=performance.now();
 function fresh(){return {id:uid('fx'),name:'새 화면 연출',asset:P.assets[0].id,when:'grabbed',key:'',threshold:1,map:'',x:60,y:10,width:35,height:70,opacity:1,duration:0,loop:true};}
 function active(){return list.find(f=>f.id===current);}
 function read(){const f=active();if(!f||!$('effectName'))return;f.name=$('effectName').value;for(const n of $('effectForm').querySelectorAll('[data-fx]'))f[n.dataset.fx]=n.type==='checkbox'?n.checked:n.type==='number'?Number(n.value):n.value;}
 function paint(){cancelAnimationFrame(previewRAF);const c=$('effectPreview'),f=active();if(!c)return;const ctx=c.getContext('2d');ctx.clearRect(0,0,640,360);ctx.fillStyle='#26354f';ctx.fillRect(0,0,640,360);ctx.fillStyle='#5b727f';ctx.fillRect(0,310,640,50);A.actor(ctx,P,{px:190,py:310,anim:'idle',facing:1},A.config(P),0);if(f){ctx.globalAlpha=f.opacity;A.frame(ctx,P,f.asset,f.x*6.4,f.y*3.6,f.width*6.4,f.height*3.6,(performance.now()-previewStart)/1000,f.loop);ctx.globalAlpha=1;ctx.strokeStyle='#e5c9ff';ctx.lineWidth=2;ctx.strokeRect(f.x*6.4,f.y*3.6,f.width*6.4,f.height*3.6);ctx.fillStyle='#e5c9ff';ctx.fillRect((f.x+f.width)*6.4-8,(f.y+f.height)*3.6-8,16,16);}previewRAF=requestAnimationFrame(paint);}
 function renderForm(){const f=active();$('effectList').innerHTML=list.map(n=>`<button data-fid="${esc(n.id)}" class="${n.id===current?'active':''}">${esc(n.name)}</button>`).join('');$('effectList').querySelectorAll('button').forEach(b=>b.onclick=()=>{read();current=b.dataset.fid;renderForm();});$('effectForm').innerHTML=f?`${field('연출 이름',inp(f.name,'id="effectName" maxlength="60"'))}${field('표시할 그림 / 애니메이션',sel(P.assets.map(a=>opt(a.id,a.name,f.asset)).join(''),'data-fx="asset"'))}<div class="row">${field('표시 조건',sel(Object.entries(conditionNames).map(([k,v])=>opt(k,v,f.when)).join(''),'data-fx="when"'))}${field('적용 맵',sel(opt('','모든 맵',f.map)+P.maps.map(m=>opt(m.id,m.name,f.map)).join(''),'data-fx="map"'))}</div>${field('스위치 / 아이템 이름',inp(f.key,'data-fx="key"'))}<div class="configGrid">${[['threshold','조건 수치',0,999,1],['x','왼쪽 위치 %',-100,100,.1],['y','위쪽 위치 %',-100,100,.1],['width','너비 %',1,200,.1],['height','높이 %',1,200,.1],['opacity','불투명도',0,1,.05],['duration','표시 초 (0=조건 유지)',0,120,.1]].map(([k,n,min,max,step])=>field(n,inp(f[k],`data-fx="${k}" type="number" min="${min}" max="${max}" step="${step}"`))).join('')}</div><label class="check"><input type="checkbox" data-fx="loop" ${f.loop?'checked':''}> 애니메이션 반복 (해제 시 마지막 프레임 유지)</label><div class="row"><button id="fxUp">겹침 순서 뒤로</button><button id="fxDown">겹침 순서 앞으로</button><button class="danger" id="fxRemove">연출 삭제</button></div>`:'<p>왼쪽에서 연출을 추가하세요.</p>';
 if(f){$('effectForm').querySelectorAll('input,select').forEach(n=>n.oninput=()=>{read();previewStart=performance.now();});$('fxRemove').onclick=()=>{list=list.filter(n=>n.id!==current);current=list[0]?.id;renderForm();};for(const [id,dir] of [['fxUp',-1],['fxDown',1]])$(id).onclick=()=>{read();const i=list.findIndex(n=>n.id===current),j=i+dir;if(j>=0&&j<list.length)[list[i],list[j]]=[list[j],list[i]];renderForm();};}paint();}
 wideModal(`<h2>조건별 화면 연출</h2><p>조건이 시작되면 처음부터 재생하고, 조건이 끝나면 숨깁니다. 목록 아래쪽이 앞에 표시됩니다. 위치·크기는 게임 화면 비율이며, 대화창과 버튼은 그림 위에 표시됩니다.</p><div class="effectLayout"><div><button id="fxAdd" class="wide">＋ 화면 연출</button><div id="effectList" class="effectList"></div></div><div><canvas id="effectPreview" class="effectPreview" width="640" height="360" aria-label="화면 연출 위치 미리보기"></canvas><p class="actionHelp">그림 영역을 드래그해 이동 · 오른쪽 아래 손잡이를 드래그해 크기 조절. 미리보기는 조건과 관계없이 표시됩니다.</p><div id="effectForm"></div></div></div><div class="actions"><button data-close>취소</button><button class="primary" id="applyEffects">모든 연출 적용</button></div>`,()=>{$('fxAdd').onclick=()=>{read();if(list.length>=50)return toast('연출은 50개까지 등록할 수 있어요.');const n=fresh();list.push(n);current=n.id;renderForm();};$('applyEffects').onclick=()=>{try{read();A.validate({...P,effects:list});checkpoint();P.effects=list;changed();$('modal').close();}catch(e){toast(e.message);}};renderForm();const c=$('effectPreview');let drag=null;c.onpointerdown=e=>{const f=active();if(!f)return;read();const r=c.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*100,y=(e.clientY-r.top)/r.height*100;drag={x,y,fx:f.x,fy:f.y,w:f.width,h:f.height,resize:Math.abs(x-f.x-f.width)<4&&Math.abs(y-f.y-f.height)<5};c.setPointerCapture(e.pointerId);};c.onpointermove=e=>{if(!drag)return;const f=active(),r=c.getBoundingClientRect(),dx=(e.clientX-r.left)/r.width*100-drag.x,dy=(e.clientY-r.top)/r.height*100-drag.y,cl=(v,a,b)=>Math.round(Math.max(a,Math.min(b,v))*10)/10;if(drag.resize){f.width=cl(drag.w+dx,1,200);f.height=cl(drag.h+dy,1,200);}else{f.x=cl(drag.fx+dx,-100,100);f.y=cl(drag.fy+dy,-100,100);}for(const k of ['x','y','width','height'])$('effectForm').querySelector(`[data-fx="${k}"]`).value=f[k];};c.onpointerup=c.onpointercancel=()=>drag=null;$('modal').addEventListener('close',()=>cancelAnimationFrame(previewRAF),{once:true});});
}
let actionRuntime=null;const runtimeRoot=document.createElement('div');runtimeRoot.id='actionRuntime';runtimeRoot.hidden=true;document.body.append(runtimeRoot);
const modernPlayer=()=>P.mode==='action'||(P.effects||[]).length||P.controls||(P.sounds||[]).length||P.assets.some(a=>a.frameDurations)||P.maps.some(m=>m.backgroundAdjust);
const previousStart=startPlay;startPlay=function(){if(!modernPlayer())return previousStart();try{E.validate(P);checkStart();actionRuntime?.destroy();runtimeRoot.hidden=false;actionRuntime=GamePlayer.mount(runtimeRoot,E.clone(P),()=>{actionRuntime.destroy();actionRuntime=null;runtimeRoot.hidden=true;draw();$('play').focus();});}catch(e){toast(e.message);}};$('play').onclick=startPlay;
const oldCheck=checkStart;checkStart=function(){oldCheck();if(P.mode==='action'){const c=A.config(P),m=P.maps.find(m=>m.id===P.start.map),b={px:(P.start.x+.5)*32,py:(P.start.y+1)*32};if(A.blocked(P,m,b,c.bodyWidth,c.bodyHeight))throw Error('주인공의 키만큼 빈 공간이 필요해요. 시작 위치와 주변 통행을 확인하세요.');for(const m of P.maps)for(const n of m.enemies||[])if(A.blocked(P,m,{px:(n.x+.5)*32,py:(n.y+1)*32},Math.min(n.width*.6,40),n.height*.8))throw Error(`‘${n.name}’의 몸이 벽이나 발판에 겹쳐 있어요.`);}};
const originalExport=exportHTML;exportHTML=function(){if(!modernPlayer())return originalExport();const data=JSON.stringify(P).replace(/</g,'\\u003c');return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(P.name)}</title><style>${window.actionPlayerCSS}</style></head><body><div id="runtime"></div><script type="application/json" id="project">${data}</script><script>${StoryEngineFactory.toString()}\n${ActionFactory.toString()}\n${GamePlayerFactory.toString()}\nconst E=StoryEngineFactory(),A=ActionFactory(E),P=E.validate(JSON.parse(document.getElementById('project').textContent));GamePlayerFactory(E,A).mount(document.getElementById('runtime'),P);</script></body></html>`;};
render();
