function StoryEngineFactory(){
 const TILE=32,clone=x=>JSON.parse(JSON.stringify(x));
 const terrain=[['grass','풀밭','#638858'],['path','흙길','#c4a47a'],['water','물','#4b87a5'],['sand','모래','#d8c390'],['floor','나무 바닥','#997653'],['stone','돌 바닥','#8b9298'],['tree','나무','#375f40'],['roof','지붕','#a75851'],['wall','집 벽','#e6d1a5'],['door','문','#684c3c'],['flower','꽃','#e3a3b6'],['chest','상자','#ac7b40']];
 terrain.push(['air','횡스크롤 빈 공간','#26354f']);
 terrain.push(['collider','투명 충돌 타일','#e85c65']);
 const builtins=terrain.map(([id,name,color])=>({id,name,color,kind:'tile',solid:['water','tree','roof','wall','chest','collider'].includes(id)}));
 function makeMap(name='새 맵',w=24,h=18){return {id:'m'+Math.random().toString(36).slice(2,10),name,w,h,ground:Array(w*h).fill('grass'),objects:Array(w*h).fill(null),collision:Array(w*h).fill(null),events:[],background:null};}
 function sample(){const m=makeMap('솔바람 마을');m.id='village';for(let y=0;y<m.h;y++)for(let x=0;x<m.w;x++){const i=y*m.w+x;if(x>19||x===19&&y%4<2)m.ground[i]='water';else if(x===18||x===19)m.ground[i]='sand';if((y===10||y===11)&&x<18||x===10&&y>5)m.ground[i]='path';if((x===1||x===2||x===16)&&y>0&&y<17&&y%3===1)m.objects[i]='tree';if(y===5&&x>=5&&x<=8||y===4&&x>=6&&x<=7)m.objects[i]='roof';if(y===6&&x>=5&&x<=8)m.objects[i]='wall';if(y===7&&x>=5&&x<=8)m.objects[i]=x===6?'door':'wall';if(y===8&&x>=12&&x<=15)m.objects[i]='flower';}
 const room=makeMap('작은 집',14,11);room.id='house';room.ground.fill('floor');for(let y=0;y<room.h;y++)for(let x=0;x<room.w;x++)if(y===0||x===0||x===room.w-1||y===room.h-1)room.objects[y*room.w+x]='wall';room.objects[9*14+7]=null;room.objects[10*14+7]=null;
 m.events=[{id:'guide',name:'마을 안내인',x:10,y:8,appearance:'npc',trigger:'action',solid:true,once:false,condition:{type:'none'},fallback:'',commands:[{type:'text',speaker:'안내인',text:'솔바람 마을에 온 걸 환영해요.\n나무 옆 상자에 작은 선물을 두었어요.'},{type:'choice',text:'이곳에서 어떤 이야기를 만들까요?',options:[{label:'따뜻한 모험',reply:'좋아요. 당신만의 모험을 시작해 보세요!',switch:'모험 시작'},{label:'신비로운 이야기',reply:'숲 너머에 어떤 비밀이 있을까요?',switch:'비밀 찾기'}]}]},
 {id:'gift',name:'열쇠 상자',x:4,y:10,appearance:'chest',trigger:'action',solid:true,once:true,condition:{type:'none'},fallback:'상자는 비어 있어요.',commands:[{type:'text',speaker:'',text:'상자에서 오래된 열쇠를 발견했다.'},{type:'item',name:'오래된 열쇠',amount:1}]},
 {id:'door',name:'집으로 들어가기',x:6,y:7,appearance:'none',trigger:'touch',solid:false,once:false,condition:{type:'item',key:'오래된 열쇠'},fallback:'문이 잠겨 있어요. 오래된 열쇠가 필요합니다.',commands:[{type:'transfer',map:'house',x:7,y:8}] }];
 room.events=[{id:'exit',name:'마을로 나가기',x:7,y:9,appearance:'none',trigger:'touch',solid:false,once:false,condition:{type:'none'},fallback:'',commands:[{type:'transfer',map:'village',x:6,y:8}]},{id:'note',name:'책상 위 편지',x:7,y:3,appearance:'chest',trigger:'action',solid:true,once:false,condition:{type:'none'},fallback:'',commands:[{type:'text',speaker:'낡은 편지',text:'이제 이 마을의 이야기는 당신의 손에 달려 있습니다.\n편집기로 돌아가 나만의 장면을 만들어 보세요.'}]}];
 return {format:'story-forge',version:1,name:'솔바람 마을의 작은 열쇠',maps:[m,room],assets:[],start:{map:m.id,x:10,y:12,sprite:'hero'}};}
 function validate(p){const fail=s=>{throw Error('프로젝트 확인: '+s)};if(!p||p.format!=='story-forge'||p.version!==1)fail('지원하지 않는 파일 형식입니다.');if(!Array.isArray(p.maps)||p.maps.length<1||p.maps.length>30)fail('맵은 1~30개여야 합니다.');if(!Array.isArray(p.assets)||p.assets.length>2048)fail('에셋이 너무 많습니다.');const ids=new Set(builtins.map(a=>a.id));for(const a of p.assets){if(!a||typeof a.id!=='string'||ids.has(a.id))fail('에셋 ID가 잘못되었습니다.');ids.add(a.id);if(a.preserveAspect!==undefined&&typeof a.preserveAspect!=='boolean')fail('원본 비율 설정이 잘못되었습니다.');if(!['tile','character','portrait','background','animation'].includes(a.kind)||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(a.data||''))fail('이미지 형식이 잘못되었습니다.');if(a.frameDurations!==undefined){if(!Array.isArray(a.frameDurations)||a.frameDurations.length!==a.frames||!Number.isInteger(a.cols)||!Number.isInteger(a.rows)||a.cols<1||a.cols>32||a.rows<1||a.rows>32||a.frames<1||a.frames>256||a.frames>a.cols*a.rows||a.frameDurations.some(d=>!Number.isFinite(d)||d<.01||d>120))fail('GIF 프레임 정보가 잘못되었습니다.');}if(a.gifData!==undefined&&!/^data:image\/gif;base64,[A-Za-z0-9+/=]+$/.test(a.gifData))fail('GIF 원본이 잘못되었습니다.');if(a.kind==='character'&&!a.frameDurations&&(![1,3].includes(a.cols)||![1,4].includes(a.rows)))fail('캐릭터 규격이 잘못되었습니다.');}
 if(p.sounds!==undefined){if(!Array.isArray(p.sounds)||p.sounds.length>100)fail('효과음은 100개까지입니다.');const soundIds=new Set();for(const a of p.sounds){if(!a||typeof a.id!=='string'||soundIds.has(a.id)||!/^data:audio\/wav;base64,[A-Za-z0-9+/=]+$/.test(a.data||'')||!Number.isFinite(a.volume)||a.volume<0||a.volume>1)fail('효과음 설정이 잘못되었습니다.');if(a.loop!==undefined&&typeof a.loop!=='boolean')fail('효과음 반복 설정');soundIds.add(a.id);}}
 if(p.controls!==undefined){if(!p.controls||typeof p.controls!=='object'||Array.isArray(p.controls))fail('키 설정');const seen=new Set();for(const [key,value] of Object.entries(controls(p))){if(!Object.hasOwn(defaultControls(p),key)||!Array.isArray(value)||value.length<1||value.length>2)fail('키 설정');for(const code of value){if(!/^(Key[A-Z]|Digit[0-9]|Arrow(Left|Right|Up|Down)|Space|Enter|ShiftLeft|ShiftRight)$/.test(code)||seen.has(code))fail('중복되거나 지원하지 않는 키입니다.');seen.add(code);}}}
 if(p.soundBindings!==undefined){if(!p.soundBindings||typeof p.soundBindings!=='object'||Array.isArray(p.soundBindings))fail('동작 효과음');for(const [k,v] of Object.entries(p.soundBindings))if(!['idle','run','jump','fall','attack','hurt','grabbed','grab','healCast','heal','prone','interact','escape'].includes(k)||v&&!(p.sounds||[]).some(a=>a.id===v))fail('동작 효과음 참조');}
 const mapids=new Set();for(const m of p.maps){if(!m||typeof m.id!=='string'||mapids.has(m.id))fail('중복된 맵 ID입니다.');mapids.add(m.id);if(m.backgroundAdjust!==undefined){const b=m.backgroundAdjust;if(!b||typeof b!=='object'||!['contain','cover','stretch'].includes(b.fit)||![b.x,b.y,b.scale,b.opacity].every(Number.isFinite)||Math.abs(b.x)>200||Math.abs(b.y)>200||b.scale<10||b.scale>400||b.opacity<0||b.opacity>1)fail('배경 조절 값');}if(m.backgroundSpace!==undefined&&!['map','screen'].includes(m.backgroundSpace))fail('배경 배치 설정이 잘못되었습니다.');if(!Number.isInteger(m.w)||!Number.isInteger(m.h)||m.w<5||m.h<5||m.w>96||m.h>96)fail('맵 크기는 5~96칸입니다.');for(const k of ['ground','objects','collision'])if(!Array.isArray(m[k])||m[k].length!==m.w*m.h)fail('맵 데이터 크기가 다릅니다.');if(m.ground.some(t=>!ids.has(t))||m.objects.some(t=>t!==null&&!ids.has(t))||m.collision.some(t=>t!==null&&typeof t!=='boolean'))fail('잘못된 타일 데이터입니다.');if(!Array.isArray(m.events)||m.events.length>500)fail('이벤트가 너무 많습니다.');const evIds=new Set();for(const e of m.events){if(!e||typeof e.id!=='string'||evIds.has(e.id)||!Number.isInteger(e.x)||!Number.isInteger(e.y)||e.x<0||e.y<0||e.x>=m.w||e.y>=m.h)fail('이벤트 위치 또는 ID가 잘못되었습니다.');evIds.add(e.id);if(!['touch','action'].includes(e.trigger)||!e.condition||!['none','switch','item'].includes(e.condition.type)||!Array.isArray(e.commands)||e.commands.length>100)fail('이벤트 설정이 잘못되었습니다.');for(const c of e.commands){if(!['text','choice','item','switch','transfer','sound'].includes(c.type))fail('알 수 없는 이벤트 명령입니다.');if(c.type==='sound'&&c.stop!==undefined&&typeof c.stop!=='boolean')fail('효과음 정지 설정');if(c.type==='sound'&&!(p.sounds||[]).some(a=>a.id===c.sound))fail('효과음 참조');if(c.type==='choice'&&(!Array.isArray(c.options)||c.options.length<1||c.options.length>4||c.options.some(o=>!o||typeof o.label!=='string')))fail('선택지가 잘못되었습니다.');if(c.type==='item'&&(!Number.isInteger(c.amount)||Math.abs(c.amount)>999))fail('아이템 수량이 잘못되었습니다.');}}}
 if(!p.start||!mapids.has(p.start.map))fail('시작 맵이 없습니다.');const start=p.maps.find(m=>m.id===p.start.map);if(!Number.isInteger(p.start.x)||!Number.isInteger(p.start.y)||p.start.x<0||p.start.y<0||p.start.x>=start.w||p.start.y>=start.h)fail('시작 위치가 잘못되었습니다.');for(const m of p.maps)for(const e of m.events)for(const c of e.commands)if(c.type==='transfer'){const dest=p.maps.find(n=>n.id===c.map);if(!dest||!Number.isInteger(c.x)||!Number.isInteger(c.y)||c.x<0||c.y<0||c.x>=dest.w||c.y>=dest.h)fail('맵 이동 목적지가 잘못되었습니다.');}return p;}
 function assets(p){return [...builtins,...p.assets];}
 function solid(p,m,x,y){if(x<0||y<0||x>=m.w||y>=m.h)return true;let i=y*m.w+x;if(m.collision[i]!==null)return m.collision[i];const list=assets(p);return !![m.ground[i],m.objects[i]].some(id=>list.find(a=>a.id===id)?.solid);}
 function createState(p){return {map:p.start.map,x:p.start.x,y:p.start.y,dir:0,step:0,inventory:Object.create(null),switches:Object.create(null),done:[],queue:[],dialog:null,event:null};}
 function next(p,s){s.dialog=null;let guard=0;while(s.queue.length&&guard++<120){const c=s.queue.shift();if(c.type==='sound'){(s.audioEvents??=[]).push(c.stop?{id:c.sound,stop:true}:c.sound);continue;}if(c.type==='text'){s.dialog={type:'text',speaker:c.speaker||'',text:c.text||'',portrait:c.portrait||null};return;}if(c.type==='choice'){s.dialog=clone(c);return;}if(c.type==='item'){const n=s.inventory[c.name]||0;s.inventory[c.name]=Math.max(0,n+c.amount);}if(c.type==='switch')s.switches[c.name]=!!c.value;if(c.type==='transfer'){s.map=c.map;s.x=c.x;s.y=c.y;}}
 if(s.event){if(s.event.once)s.done.push(s.event.key);s.event=null;}}
 function trigger(p,s,e){if(s.dialog||s.event)return false;const key=s.map+':'+e.id,cond=e.condition||{type:'none'},ok=cond.type==='none'||cond.type==='switch'&&!!s.switches[cond.key]||cond.type==='item'&&(s.inventory[cond.key]||0)>0;if(!ok||e.once&&s.done.includes(key)){if(e.fallback)s.dialog={type:'text',speaker:e.name,text:e.fallback};return true;}s.event={key,once:e.once};s.queue=clone(e.commands);next(p,s);return true;}
 function interact(p,s){if(s.dialog)return false;const m=p.maps.find(m=>m.id===s.map),d=[[0,1],[-1,0],[1,0],[0,-1]][s.dir];const e=m.events.find(e=>e.trigger==='action'&&e.x===s.x+d[0]&&e.y===s.y+d[1])||m.events.find(e=>e.trigger==='action'&&e.x===s.x&&e.y===s.y);return e?trigger(p,s,e):false;}
 function move(p,s,dx,dy){if(s.dialog)return false;s.dir=dy>0?0:dx<0?1:dx>0?2:3;const m=p.maps.find(m=>m.id===s.map),x=s.x+dx,y=s.y+dy;if(solid(p,m,x,y)||m.events.some(e=>e.solid&&e.x===x&&e.y===y))return false;s.x=x;s.y=y;s.step++;const e=m.events.find(e=>e.trigger==='touch'&&e.x===x&&e.y===y);if(e)trigger(p,s,e);return true;}
 function choose(p,s,i){if(s.dialog?.type!=='choice')return;const o=s.dialog.options[i];if(!o)return;if(o.switch)s.switches[o.switch]=true;if(o.reply)s.queue.unshift({type:'text',text:o.reply});next(p,s);}
 const cache={};function image(a){if(!cache[a.id]||cache[a.id].src!==a.data){const im=new Image();im.onload=()=>window.dispatchEvent(new Event('assetloaded'));im.src=a.data;cache[a.id]=im;}return cache[a.id];}
 function fitRect(sw,sh,x,y,w,h,keep=false,anchorY=.5){if(!keep||!(sw>0&&sh>0))return {x,y,w,h};const scale=Math.min(w/sw,h/sh),nw=sw*scale,nh=sh*scale;return {x:x+(w-nw)/2,y:y+(h-nh)*anchorY,w:nw,h:nh};}

 function defaultControls(p){return p.mode==='action'?{left:['ArrowLeft','KeyA'],right:['ArrowRight','KeyD'],jump:['Space'],attack:['KeyZ'],escape:['KeyX'],heal:['KeyC'],prone:['ArrowDown','KeyS'],interact:['Enter'],bag:['KeyI']}:{left:['ArrowLeft','KeyA'],right:['ArrowRight','KeyD'],up:['ArrowUp','KeyW'],down:['ArrowDown','KeyS'],interact:['Enter','Space'],bag:['KeyI']};}
 function controls(p){const c={...defaultControls(p),...p.controls};if(p.mode==='action'&&p.controls&&!Object.hasOwn(p.controls,'prone')){const used=new Set(Object.entries(c).filter(([k])=>k!=='prone').flatMap(([,v])=>Array.isArray(v)?v:[]));c.prone=c.prone.filter(k=>!used.has(k));if(!c.prone.length)c.prone=[Array.from('PVBNMQLKJHGFDSAZXCEWRTYUO').map(k=>'Key'+k).find(k=>!used.has(k))||'ShiftRight'];}return c;}
 function keyName(code){return ({Space:'Space',Enter:'Enter',ArrowLeft:'←',ArrowRight:'→',ArrowUp:'↑',ArrowDown:'↓',ShiftLeft:'왼쪽 Shift',ShiftRight:'오른쪽 Shift'})[code]||code.replace(/^(Key|Digit)/,'');}
 function frameIndex(a,time=0,loop=true){const count=a.frames||1;if(a.frameDurations){const total=a.frameDurations.reduce((x,y)=>x+y,0);let t=Math.max(0,time);if(!loop&&t>=total)return count-1;t%=total;for(let i=0;i<count;i++){if(t<a.frameDurations[i])return i;t-=a.frameDurations[i];}return count-1;}const i=Math.floor(Math.max(0,time)*(a.fps||8));return loop?i%count:Math.min(i,count-1);}
 function backgroundRect(a,sw,sh,w,h,b){b=b||{fit:a.preserveAspect?'contain':'stretch',x:0,y:0,scale:100,opacity:1};let r=b.fit==='cover'?(()=>{const k=Math.max(w/sw,h/sh);return {x:(w-sw*k)/2,y:(h-sh*k)/2,w:sw*k,h:sh*k};})():fitRect(sw,sh,0,0,w,h,b.fit==='contain');const k=b.scale/100;return {x:r.x+(r.w-r.w*k)/2+w*b.x/100,y:r.y+(r.h-r.h*k)/2+h*b.y/100,w:r.w*k,h:r.h*k,opacity:b.opacity};}
 function drawBackground(ctx,p,m,w,h,time=0){const a=p.assets.find(a=>a.id===m.background);if(!a)return;const im=image(a);if(!im.complete||!im.naturalWidth)return;const cols=a.cols||1,rows=a.rows||1,sw=im.naturalWidth/cols,sh=im.naturalHeight/rows,i=frameIndex(a,time),r=backgroundRect(a,sw,sh,w,h,m.backgroundAdjust);ctx.save();ctx.globalAlpha=r.opacity;ctx.drawImage(im,i%cols*sw,Math.floor(i/cols)*sh,sw,sh,r.x,r.y,r.w,r.h);ctx.restore();}
 function drawAsset(ctx,p,id,x,y,size=32,dir=0,step=0,time=0){if(!id||id==='none'||id==='air'||id==='collider')return;const a=assets(p).find(a=>a.id===id);if(a?.data){const im=image(a);if(im.complete&&im.naturalWidth){let cols=a.cols||1,rows=a.rows||1,w=im.naturalWidth/cols,h=im.naturalHeight/rows;const r=fitRect(w,h,x,y,size,size,a.preserveAspect,a.kind==='character'?1:.5);const i=frameIndex(a,time);ctx.drawImage(im,(a.frameDurations?i%cols:cols>1?step%cols:0)*w,(a.frameDurations?Math.floor(i/cols):rows>1?dir:0)*h,w,h,r.x,r.y,r.w,r.h);}return;}
 ctx.save();ctx.translate(x,y);ctx.scale(size/32,size/32);ctx.imageSmoothingEnabled=false;
 if(['hero','npc'].includes(id)){ctx.fillStyle='#0003';ctx.fillRect(8,27,17,4);ctx.fillStyle=id==='hero'?'#dda5ce':'#efc66a';ctx.fillRect(10,16,13,11);ctx.fillStyle='#f3d2a4';ctx.fillRect(10,5,13,12);ctx.fillStyle=id==='hero'?'#624b79':'#694f3b';ctx.fillRect(9,3,15,6);ctx.fillRect(8,7,4,8);ctx.fillStyle='#34334a';ctx.fillRect(11,27,4,4);ctx.fillRect(19,27,4,4);ctx.fillStyle='#302c38';if(dir!==3){ctx.fillRect(dir===1?10:14,11,2,2);if(dir===0)ctx.fillRect(20,11,2,2);}ctx.restore();return;}
 if(id==='tree'){ctx.fillStyle='#473f32';ctx.fillRect(13,20,6,12);ctx.fillStyle='#284e37';ctx.fillRect(5,10,24,15);ctx.fillStyle='#3c6a45';ctx.fillRect(3,6,24,15);ctx.fillRect(8,1,16,9);ctx.fillStyle='#568651';ctx.fillRect(8,5,12,5);}
 else if(id==='flower'){ctx.fillStyle='#497444';ctx.fillRect(8,16,3,12);ctx.fillRect(23,13,3,15);ctx.fillStyle='#f0c1ca';ctx.fillRect(5,10,9,8);ctx.fillRect(19,7,10,8);ctx.fillStyle='#efd892';ctx.fillRect(8,12,3,3);ctx.fillRect(22,9,3,3);}
 else if(id==='chest'){ctx.fillStyle='#533a2d';ctx.fillRect(5,11,23,18);ctx.fillStyle='#b48049';ctx.fillRect(5,8,23,11);ctx.fillStyle='#e0b967';ctx.fillRect(8,8,3,20);ctx.fillRect(23,8,3,20);ctx.fillRect(15,18,5,5);}
 else{ctx.fillStyle=a?.color||'#638858';ctx.fillRect(0,0,32,32);if(id==='grass'){ctx.fillStyle='#779761';ctx.fillRect(4,9,3,2);ctx.fillRect(22,24,3,2);ctx.fillStyle='#577b50';ctx.fillRect(12,18,2,3);}if(id==='water'){ctx.fillStyle='#74a9bd';ctx.fillRect(3,10,13,2);ctx.fillRect(18,23,11,2);}if(id==='path'||id==='sand'){ctx.fillStyle='#ab8f632f';ctx.fillRect(6,8,3,2);ctx.fillRect(21,22,3,2);}if(id==='floor'){ctx.fillStyle='#644f45';ctx.fillRect(0,15,32,1);ctx.fillRect(0,31,32,1);ctx.fillRect(9,0,1,15);ctx.fillRect(25,16,1,16);}if(id==='roof'){ctx.fillStyle='#79494a';for(let i=7;i<32;i+=8)ctx.fillRect(0,i,32,2);}if(id==='wall'){ctx.fillStyle='#97784d';ctx.fillRect(0,0,3,32);ctx.fillRect(29,0,3,32);ctx.fillRect(0,29,32,3);}if(id==='door'){ctx.fillStyle='#dcb98a';ctx.fillRect(0,0,4,32);ctx.fillRect(28,0,4,32);ctx.fillRect(0,0,32,4);ctx.fillStyle='#e1bd66';ctx.fillRect(21,18,3,3);}if(id==='stone'){ctx.strokeStyle='#737e87';ctx.strokeRect(1,1,30,30);}}
 ctx.restore();}
 function drawMap(ctx,p,m,size=32,{grid=false,collision=false,events=true,state=null,start=false,time=state?.time||0}={}){ctx.clearRect(0,0,m.w*size,m.h*size);const bg=p.assets.find(a=>a.id===m.background);drawBackground(ctx,p,m,m.w*size,m.h*size,time);for(let y=0;y<m.h;y++)for(let x=0;x<m.w;x++){const i=y*m.w+x;ctx.globalAlpha=bg?0.76:1;drawAsset(ctx,p,m.ground[i],x*size,y*size,size,0,0,time);ctx.globalAlpha=1;drawAsset(ctx,p,m.objects[i],x*size,y*size,size,0,0,time);if(collision&&solid(p,m,x,y)){ctx.fillStyle='#e85c6555';ctx.fillRect(x*size,y*size,size,size);}if(grid){ctx.strokeStyle='#18281b25';ctx.strokeRect(x*size,y*size,size,size);}}
 for(const e of m.events){drawAsset(ctx,p,e.appearance,e.x*size,e.y*size,size,0,0,time);if(events){ctx.strokeStyle='#b6a0f8';ctx.lineWidth=2;ctx.strokeRect(e.x*size+2,e.y*size+2,size-4,size-4);ctx.fillStyle='#322b4e';ctx.fillRect(e.x*size+1,e.y*size+1,15,15);ctx.fillStyle='#eee';ctx.font='bold 10px sans-serif';ctx.fillText('E',e.x*size+5,e.y*size+12);}}
 if(start&&p.start.map===m.id){drawAsset(ctx,p,p.start.sprite,p.start.x*size,p.start.y*size,size,0,0,time);ctx.strokeStyle='#f6d779';ctx.lineWidth=2;ctx.strokeRect(p.start.x*size,p.start.y*size,size,size);}
 if(state)drawAsset(ctx,p,p.start.sprite,state.x*size,state.y*size,size,state.dir,state.step,time);
 }
 return {TILE,clone,builtins,makeMap,sample,validate,assets,solid,createState,next,trigger,interact,move,choose,fitRect,drawAsset,drawMap,frameIndex,drawBackground,backgroundRect,defaultControls,controls,keyName};
}
if(typeof module!=='undefined'){module.exports=StoryEngineFactory();require('./action.js')(module.exports);}
else window.Engine=StoryEngineFactory();
