'use strict';
// Import GIF frames once; saved projects/HTML play without decoder dependencies.
async function gifAsset(file){
 if(file.size>12*1024*1024)throw Error('GIF는 12MB 이하로 넣어주세요.');
 if(typeof ImageDecoder==='undefined')throw Error('GIF 불러오기는 PC 설치판 또는 최신 Chrome / Edge에서 사용할 수 있어요.');
 const bytes=await file.arrayBuffer(),decoder=new ImageDecoder({data:bytes,type:'image/gif',preferAnimation:true});
 try{await decoder.tracks.ready;const count=decoder.tracks.selectedTrack.frameCount;if(count<1||count>256)throw Error('GIF는 1~256프레임으로 넣어주세요.');
 const first=await decoder.decode({frameIndex:0}),w=first.image.displayWidth,h=first.image.displayHeight;first.image.close();
 const cols=Math.min(count,32,Math.max(1,Math.floor(4096/w))),rows=Math.ceil(count/cols);
 if(w>4096||h>4096||rows>32||h*rows>8192||w*cols*h*rows>16777216)throw Error('GIF 해상도나 프레임 수가 너무 큽니다. 크기를 줄여주세요.');
 const canvas=document.createElement('canvas');canvas.width=w*cols;canvas.height=h*rows;const ctx=canvas.getContext('2d'),frameDurations=[];
 for(let i=0;i<count;i++){const {image}=await decoder.decode({frameIndex:i});try{ctx.drawImage(image,i%cols*w,Math.floor(i/cols)*h);frameDurations.push(Math.max(.01,(image.duration||100000)/1e6));}finally{image.close();}}
 return {data:canvas.toDataURL('image/png'),cols,rows,frames:count,fps:8,frameDurations};
 }finally{decoder.close();}
}
function fileData(file,type){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(Error('파일을 읽을 수 없어요.'));reader.onload=()=>resolve(String(reader.result).replace(/^data:[^;]*;/,`data:${type};`));reader.readAsDataURL(file);});}
function addMediaAsset(a){const next={...P,assets:[...P.assets,a]};E.validate(next);if(JSON.stringify(next).length>60*1024*1024)throw Error('프로젝트는 60MB 이내로 유지해 주세요.');checkpoint();P.assets.push(a);selected=a.id;tab=a.kind==='character'?'character':a.kind==='tile'?'tile':'other';document.querySelectorAll('[data-tab]').forEach(n=>n.classList.toggle('active',n.dataset.tab===tab));changed();$('modal').close();render();}
async function importGif(file,motion=false){try{toast('GIF 프레임을 읽고 있어요.');const asset=await gifAsset(file),raw=await fileData(file,'image/gif');modal(`<h2>GIF 애니메이션 불러오기</h2><img class="sheetPreview" src="${raw}" alt="GIF 미리보기"><p>${asset.frames}프레임 · 원본 프레임 간격을 유지합니다.</p>${field('그림 이름',inp(file.name.replace(/\.[^.]+$/,''),'id="gifName" maxlength="60"'))}${field('사용할 곳',sel([['animation','캐릭터 동작 / 화면 연출'],['character','캐릭터'],['background','맵 배경'],['tile','움직이는 타일'],['portrait','대화 얼굴 그림']].map(([k,n])=>opt(k,n,motion?'animation':'character')).join(''),'id="gifKind"'))}<label class="check"><input id="gifAspect" type="checkbox" checked> 원본 비율 유지</label><div class="actions"><button data-close>취소</button><button id="addGif" class="primary">불러오기</button></div>`,()=>{$('addGif').onclick=()=>{try{const kind=$('gifKind').value;addMediaAsset({...asset,id:uid('gif'),name:$('gifName').value.trim()||'GIF',kind,preserveAspect:$('gifAspect').checked,...(kind==='portrait'?{gifData:raw}:{})});toast('GIF 애니메이션을 등록했어요.');}catch(e){toast(e.message);}};});}catch(e){toast(e.message);}}
for(const [input,isMotion] of [[$('assetFile'),false],[$('motionFile'),true]]){input.accept+=',image/gif';const previous=input.onchange;input.onchange=async e=>{const file=input.files[0];if(file&&(file.type==='image/gif'||/\.gif$/i.test(file.name))){input.value='';await importGif(file,isMotion);}else await previous(e);};}
const mediaButtons=document.createElement('div');mediaButtons.className='row';mediaButtons.innerHTML='<button id="soundSettings">WAV 효과음</button><button id="keySettings">조작 키 설정</button>';modePanel.append(mediaButtons);
const backgroundButton=document.createElement('button');backgroundButton.id='backgroundSettings';backgroundButton.className='quiet wide';backgroundButton.textContent='배경 위치 · 크기 조절';$('mapSettings').after(backgroundButton);
const keyLabels={left:'왼쪽 이동',right:'오른쪽 이동',up:'위로 이동',down:'아래로 이동',jump:'점프',attack:'공격',escape:'잡힘 탈출',heal:'회복',prone:'엎드리기 (누르는 동안)',interact:'조사 / 대화',bag:'가방'};
$('keySettings').onclick=()=>{let c=E.clone(E.controls(P));wideModal(`<h2>동작별 조작 키</h2><p>버튼을 누른 뒤 사용할 키를 누르세요. 보조 키는 ‘없음’으로 지울 수 있습니다. Esc는 편집기로 돌아가기, 대화 선택지의 숫자 1~4는 선택 용도로 우선 사용합니다.</p><div id="keyFields" class="clipGrid"></div><div class="actions"><button id="resetKeys">기본값</button><button data-close>취소</button><button id="applyKeys" class="primary">적용</button></div>`,()=>{
 function fields(){ $('keyFields').innerHTML=Object.entries(c).map(([k,keys])=>`<div class="field">${keyLabels[k]}<div class="row"><button data-bind="${k}" data-slot="0">${esc(E.keyName(keys[0]))}</button><button data-bind="${k}" data-slot="1">${keys[1]?esc(E.keyName(keys[1])):'보조 키 없음'}</button><button data-clear="${k}">없음</button></div></div>`).join('');$('keyFields').querySelectorAll('[data-bind]').forEach(b=>b.onclick=()=>{b.textContent='키를 누르세요…';b.focus();b.onkeydown=e=>{e.preventDefault();e.stopPropagation();const code=e.code;if(!/^(Key[A-Z]|Digit[0-9]|Arrow(Left|Right|Up|Down)|Space|Enter|ShiftLeft|ShiftRight)$/.test(code)||e.ctrlKey||e.altKey||e.metaKey)return toast('영문·숫자·방향키·Space·Enter·Shift를 사용하세요.');const draft=E.clone(c);draft[b.dataset.bind][Number(b.dataset.slot)]=code;try{E.validate({...P,controls:draft});c=draft;fields();}catch(err){toast(err.message);}};});$('keyFields').querySelectorAll('[data-clear]').forEach(b=>b.onclick=()=>{c[b.dataset.clear]=c[b.dataset.clear].slice(0,1);fields();});}
 $('resetKeys').onclick=()=>{c=E.defaultControls(P);fields();};$('applyKeys').onclick=()=>{try{E.validate({...P,controls:c});checkpoint();P.controls=c;changed();$('modal').close();}catch(e){toast(e.message);}};fields();});};
$('soundSettings').onclick=()=>{let sounds=E.clone(P.sounds||[]),bindings=E.clone(P.soundBindings||{}),preview=null;const labels={...motionNames,interact:'조사 / 대화',escape:'잡힘 탈출 완료'};wideModal(`<h2>WAV 효과음</h2><p>반복을 켜면 동작이 유지되는 동안 재생하고 동작이 끝나면 멈춥니다. 이벤트의 반복음은 ‘효과음 정지’ 명령이나 맵 이동 시 멈춥니다. 조사·탈출 효과음은 한 번 재생합니다. 삭제 후 적용하면 이 소리를 쓰던 동작·이벤트 연결도 제거됩니다.</p><input type="file" id="wavFile" accept=".wav,audio/wav,audio/x-wav" hidden><button id="importWav">＋ WAV 불러오기</button><div id="soundList"></div><h3>동작에 연결</h3><div id="soundBindings" class="clipGrid"></div><div class="actions"><button data-close>취소</button><button id="applySounds" class="primary">적용</button></div>`,()=>{
 const stop=()=>{preview?.pause();preview=null;};$('modal').addEventListener('close',stop,{once:true});
 function fields(){ $('soundList').innerHTML=sounds.map(a=>`<div class="row soundRow"><span>${esc(a.name)}</span>${field('음량',inp(a.volume,`data-volume="${a.id}" type="range" min="0" max="1" step=".05"`))}<label class="check"><input type="checkbox" data-loop="${a.id}" ${a.loop?'checked':''}> 반복</label><button data-listen="${a.id}">듣기 / 정지</button><button class="danger" data-delete-sound="${a.id}">삭제</button></div>`).join('');$('soundBindings').innerHTML=Object.entries(labels).map(([k,n])=>field(n,sel(opt('','없음',bindings[k]||'')+sounds.map(a=>opt(a.id,a.name,bindings[k])).join(''),`data-sound="${k}"`))).join('');$('soundBindings').querySelectorAll('select').forEach(n=>n.onchange=()=>bindings[n.dataset.sound]=n.value);$('soundList').querySelectorAll('[data-volume]').forEach(n=>n.oninput=()=>{sounds.find(a=>a.id===n.dataset.volume).volume=Number(n.value);});$('soundList').querySelectorAll('[data-listen]').forEach(b=>b.onclick=()=>{if(preview?.dataset.soundId===b.dataset.listen){stop();return;}stop();const a=sounds.find(a=>a.id===b.dataset.listen);preview=new Audio(a.data);preview.dataset.soundId=a.id;preview.volume=a.volume;preview.loop=!!a.loop;preview.play().catch(()=>toast('효과음을 재생할 수 없어요.'));});$('soundList').querySelectorAll('[data-loop]').forEach(n=>n.onchange=()=>{const a=sounds.find(a=>a.id===n.dataset.loop);a.loop=n.checked;if(preview?.dataset.soundId===a.id)preview.loop=n.checked;});$('soundList').querySelectorAll('[data-delete-sound]').forEach(b=>b.onclick=()=>{const id=b.dataset.deleteSound;if(preview?.dataset.soundId===id)stop();sounds=sounds.filter(a=>a.id!==id);for(const k of Object.keys(bindings))if(bindings[k]===id)bindings[k]='';fields();});}
 $('importWav').onclick=()=>$('wavFile').click();$('wavFile').onchange=async()=>{const f=$('wavFile').files[0];$('wavFile').value='';if(!f)return;try{if(f.size>12*1024*1024)throw Error('효과음 하나는 12MB 이하로 넣어주세요.');const bytes=await f.arrayBuffer(),head=new TextDecoder().decode(bytes.slice(0,12));if(!head.startsWith('RIFF')||head.slice(8)!=='WAVE')throw Error('WAV 파일을 선택하세요.');const audioContext=new AudioContext();try{const decoded=await audioContext.decodeAudioData(bytes);if(decoded.duration>30)throw Error('효과음은 30초 이하로 넣어주세요.');}finally{await audioContext.close();}const a={id:uid('sound'),name:f.name.replace(/\.wav$/i,''),volume:1,data:await fileData(f,'audio/wav')};const next={...P,sounds:[...(P.sounds||[]),...sounds.filter(s=>!(P.sounds||[]).some(a=>a.id===s.id)),a]};E.validate(next);if(JSON.stringify(next).length>60*1024*1024)throw Error('프로젝트는 60MB 이내로 유지해 주세요.');sounds.push(a);fields();}catch(e){toast(e.message);}};
 $('applySounds').onclick=()=>{try{const ids=new Set(sounds.map(a=>a.id)),maps=P.maps.map(m=>({...m,events:m.events.map(e=>({...e,commands:e.commands.filter(c=>c.type!=='sound'||ids.has(c.sound))}))}));E.validate({...P,maps,sounds,soundBindings:bindings});checkpoint();P.maps=maps;P.sounds=sounds;P.soundBindings=bindings;changed();$('modal').close();renderInspector();}catch(e){toast(e.message);}};fields();});};
$('backgroundSettings').onclick=()=>{const m=map(),asset=P.assets.find(a=>a.id===m.background);let draft=E.clone(m);draft.backgroundAdjust??={fit:asset?.preserveAspect?'contain':'stretch',x:0,y:0,scale:100,opacity:1};let raf=0,start=performance.now();wideModal(`<h2>배경 조절</h2>${field('배경 그림',sel(opt('','없음',m.background||'')+P.assets.filter(a=>a.kind==='background').map(a=>opt(a.id,a.name,m.background)).join(''),'id="adjustBG"'))}${P.mode==='action'?field('배경 배치',sel(opt('map','맵 전체 · 스크롤',m.backgroundSpace||'screen')+opt('screen','화면 고정',m.backgroundSpace||'screen'),'id="adjustSpace"')):''}<canvas id="backgroundPreview" class="effectPreview" width="640" height="360" aria-label="배경 조절 미리보기"></canvas><p>미리보기에서 드래그해 위치를 옮길 수 있습니다. 위치는 배치 영역에 대한 비율입니다.</p>${field('그림 맞춤',sel([['contain','전체 보기 · 비율 유지'],['cover','영역 채우기 · 비율 유지'],['stretch','영역에 늘이기']].map(([v,n])=>opt(v,n,draft.backgroundAdjust.fit)).join(''),'id="bgFit"'))}<div class="configGrid">${[['x','가로 위치 %',-200,200,1],['y','세로 위치 %',-200,200,1],['scale','크기 %',10,400,1],['opacity','불투명도',0,1,.05]].map(([k,n,min,max,step])=>field(n,inp(draft.backgroundAdjust[k],`data-bg="${k}" type="number" min="${min}" max="${max}" step="${step}"`))).join('')}</div><div class="actions"><button id="resetBG">위치·크기 초기화</button><button data-close>취소</button><button id="applyBG" class="primary">적용</button></div>`,()=>{
 function read(){draft.background=$('adjustBG').value||null;if($('adjustSpace'))draft.backgroundSpace=$('adjustSpace').value;draft.backgroundAdjust.fit=$('bgFit').value;$('modalContent').querySelectorAll('[data-bg]').forEach(n=>draft.backgroundAdjust[n.dataset.bg]=Number(n.value));}
 function paint(){const cv=$('backgroundPreview');if(!cv)return;read();const ctx=cv.getContext('2d');ctx.clearRect(0,0,640,360);ctx.fillStyle='#26354f';ctx.fillRect(0,0,640,360);const mw=draft.backgroundSpace==='screen'&&P.mode==='action'?640:draft.w*32,mh=draft.backgroundSpace==='screen'&&P.mode==='action'?360:draft.h*32,k=Math.min(640/mw,360/mh);ctx.save();ctx.translate((640-mw*k)/2,(360-mh*k)/2);ctx.scale(k,k);ctx.beginPath();ctx.rect(0,0,mw,mh);ctx.clip();E.drawBackground(ctx,P,draft,mw,mh,(performance.now()-start)/1000);ctx.strokeStyle='#d5c5ff';ctx.lineWidth=2/k;ctx.strokeRect(0,0,mw,mh);ctx.restore();raf=requestAnimationFrame(paint);}
 $('resetBG').onclick=()=>{for(const [k,v] of Object.entries({x:0,y:0,scale:100,opacity:1}))$('modalContent').querySelector(`[data-bg="${k}"]`).value=v;};$('applyBG').onclick=()=>{try{read();E.validate({...P,maps:P.maps.map(n=>n.id===m.id?draft:n)});checkpoint();Object.assign(m,{background:draft.background,backgroundAdjust:draft.backgroundAdjust,...(draft.backgroundSpace?{backgroundSpace:draft.backgroundSpace}:{})});changed();$('modal').close();draw();}catch(e){toast(e.message);}};
 const cv=$('backgroundPreview');let drag;cv.onpointerdown=e=>{read();const r=cv.getBoundingClientRect(),mw=draft.backgroundSpace==='screen'&&P.mode==='action'?640:draft.w*32,mh=draft.backgroundSpace==='screen'&&P.mode==='action'?360:draft.h*32,k=Math.min(r.width/mw,r.height/mh);drag={x:e.clientX,y:e.clientY,bx:draft.backgroundAdjust.x,by:draft.backgroundAdjust.y,w:mw*k,h:mh*k};cv.setPointerCapture(e.pointerId);};cv.onpointermove=e=>{if(!drag)return;for(const [key,value] of [['x',drag.bx+(e.clientX-drag.x)/drag.w*100],['y',drag.by+(e.clientY-drag.y)/drag.h*100]])$('modalContent').querySelector(`[data-bg="${key}"]`).value=Math.round(Math.max(-200,Math.min(200,value)));};cv.onpointerup=cv.onpointercancel=()=>drag=null;$('modal').addEventListener('close',()=>cancelAnimationFrame(raf),{once:true});paint();});};
// Animate GIF assets in the editor without changing saved state or creating undo entries.
let mediaLast=0;function mediaPreview(now){if(now-mediaLast>100&&!$('modal').open&&!actionRuntime&&!playState&&P.assets.some(a=>a.frameDurations)){mediaLast=now;draw();}requestAnimationFrame(mediaPreview);}requestAnimationFrame(mediaPreview);
