'use strict';
function GamePlayerFactory(E,A){
 function mount(root,p,onExit){
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 root.innerHTML=`<div class="actionPlayer"><div class="actionHeader"><strong>${esc(p.name)}</strong><span class="actionStatus"></span><button data-bag>가방</button><button data-restart>처음부터</button>${onExit?'<button data-exit>편집기로 · Esc</button>':''}</div><div class="actionViewport"><canvas aria-label="게임 화면"></canvas><div class="actionDialogue" hidden></div><div class="actionBag" hidden></div><div class="actionDead" hidden><h2>모험이 끝났어요</h2><button data-retry>다시 시작</button></div></div><div class="actionControls"><span>${p.mode==='action'?'← → / A D 이동 · Space 점프 · Z 공격 · X 연타 탈출 · Enter 조사':'방향키 / WASD 이동 · Enter / Space 조사'}</span><button data-key="ArrowLeft">←</button><button data-key="ArrowRight">→</button>${p.mode==='action'?'<button data-key=" ">점프</button><button data-key="z">공격</button><button data-key="x">탈출</button>':'<button data-key="ArrowUp">↑</button><button data-key="ArrowDown">↓</button>'}<button data-key="Enter">조사 / 대화</button></div></div>`;
 const $=q=>root.querySelector(q),canvas=$('canvas'),ctx=canvas.getContext('2d'),view=$('.actionViewport'),dialog=$('.actionDialogue'),bag=$('.actionBag'),dead=$('.actionDead'),status=$('.actionStatus'),held=new Set(),edge=new Set();let s,raf=0,last=performance.now(),moveClock=0,dialogSignature='',destroyed=false,paused=false;
 function reset(){s=p.mode==='action'?A.create(p):E.createState(p);s.effectState={};held.clear();edge.clear();bag.hidden=true;dead.hidden=true;dialogSignature='';moveClock=0;last=performance.now();}
 function bagView(){bag.innerHTML='<b>소지품</b>'+Object.entries(s.inventory).filter(([,v])=>v>0).map(([k,v])=>`<p>${esc(k)} × ${v}</p>`).join('')+'<p>I 또는 가방 버튼으로 닫기</p>';}
 function key(k,repeat=false){if(k==='Escape'&&onExit){onExit();return;}if(k.toLowerCase()==='i'&&!repeat){bag.hidden=!bag.hidden;bagView();held.clear();edge.clear();return;}if(!bag.hidden||s.dead)return;if(s.dialog){if(repeat)return;if(s.dialog.type==='choice'&&/^[1-4]$/.test(k))E.choose(p,s,+k-1);else if(s.dialog.type==='text'&&['Enter',' '].includes(k))E.next(p,s);if(p.mode==='action')A.enter(p,s);return;}held.add(k);if(!repeat)edge.add(k);}
 function down(e){if(!root.isConnected)return;e.stopImmediatePropagation();if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','Enter','Escape','a','d','w','s','z','x','i','1','2','3','4'].includes(e.key)){e.preventDefault();e.stopImmediatePropagation();key(e.key,e.repeat);}}
 function up(e){held.delete(e.key);}
 function clear(){held.clear();edge.clear();paused=true;}
 function focus(){paused=false;last=performance.now();}
 function paintDialogue(){const sig=JSON.stringify(s.dialog);if(sig===dialogSignature)return;dialogSignature=sig;dialog.hidden=!s.dialog;if(!s.dialog){dialog.innerHTML='';return;}held.clear();edge.clear();const d=s.dialog,portrait=p.assets.find(a=>a.id===d.portrait);dialog.innerHTML=(portrait?`<img alt="" src="${esc(portrait.data)}">`:'')+(d.speaker?`<b>${esc(d.speaker)}</b>`:'')+`<p>${esc(d.text)}</p>`+(d.type==='choice'?d.options.map((o,i)=>`<button data-choice="${i}">${i+1}. ${esc(o.label)}</button>`).join(''):'<small>Enter / Space 또는 클릭해서 계속</small>');dialog.querySelectorAll('[data-choice]').forEach(b=>b.onclick=e=>{e.stopPropagation();E.choose(p,s,+b.dataset.choice);if(p.mode==='action')A.enter(p,s);});}
 function loop(now){if(destroyed)return;const dt=Math.min((now-last)/1000,1/30);last=now;const w=Math.max(320,view.clientWidth),h=Math.max(200,view.clientHeight);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}const action=p.mode==='action';
 if(!paused&&!document.hidden&&bag.hidden){if(action)A.tick(p,s,dt,{left:held.has('ArrowLeft')||held.has('a'),right:held.has('ArrowRight')||held.has('d'),jump:edge.has(' '),attack:edge.has('z'),escape:edge.has('x'),interact:edge.has('Enter')});else if(!s.dialog){moveClock-=dt;const dirs={ArrowLeft:[-1,0],a:[-1,0],ArrowRight:[1,0],d:[1,0],ArrowUp:[0,-1],w:[0,-1],ArrowDown:[0,1],s:[0,1]},k=[...held].find(k=>dirs[k]);if(k&&(moveClock<=0||edge.has(k))){E.move(p,s,...dirs[k]);moveClock=.12;}if(edge.has('Enter')||edge.has(' '))E.interact(p,s);}}
 edge.clear();if(action){A.draw(ctx,p,s,w,h);status.textContent=s.grab?`잡힘 · X 탈출 ${s.grab.presses}/${s.grab.required} · ${s.grab.time.toFixed(1)}초`:`체력 ${s.hp}/${A.config(p).hp}`;dead.hidden=!s.dead;}else{const m=p.maps.find(m=>m.id===s.map),sz=32,cx=Math.max(0,Math.min(m.w*sz-w,(s.x+.5)*sz-w/2)),cy=Math.max(0,Math.min(m.h*sz-h,(s.y+.5)*sz-h/2));ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(-cx,-cy);E.drawMap(ctx,p,m,sz,{events:false,state:s});ctx.restore();status.textContent=m.name;}
 A.effects(ctx,p,s,w,h,paused||!bag.hidden||s.dialog?0:dt);paintDialogue();if(!bag.hidden)bagView();raf=requestAnimationFrame(loop);}
 dialog.onclick=()=>{if(s.dialog?.type==='text'){E.next(p,s);if(p.mode==='action')A.enter(p,s);}};$('[data-bag]').onclick=()=>key('i');$('[data-restart]').onclick=reset;$('[data-retry]').onclick=reset;if(onExit)$('[data-exit]').onclick=onExit;
 root.querySelectorAll('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);key(b.dataset.key);};b.onpointerup=b.onpointercancel=()=>held.delete(b.dataset.key);});
 document.addEventListener('keydown',down,true);document.addEventListener('keyup',up,true);window.addEventListener('blur',clear);window.addEventListener('focus',focus);reset();raf=requestAnimationFrame(loop);
 return {get state(){return s;},reset,destroy(){destroyed=true;cancelAnimationFrame(raf);document.removeEventListener('keydown',down,true);document.removeEventListener('keyup',up,true);window.removeEventListener('blur',clear);window.removeEventListener('focus',focus);root.innerHTML='';}};
 }
 return {mount};
}
if(typeof module!=='undefined')module.exports=GamePlayerFactory;else window.GamePlayer=GamePlayerFactory(window.Engine,window.Action);
