'use strict';
function GamePlayerFactory(E,A){
 function mount(root,p,onExit){
 const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const bindings=E.controls(p),action=p.mode==='action',labels={left:'왼쪽',right:'오른쪽',up:'위',down:'아래',jump:'점프',attack:'공격',escape:'탈출',heal:'회복',prone:'엎드리기',interact:'조사 / 대화',bag:'가방'},keyLabel=k=>(bindings[k]||[]).map(E.keyName).join(' / ');
 root.innerHTML=`<div class="actionPlayer"><div class="actionHeader"><strong>${esc(p.name)}</strong><span class="actionStatus"></span><button data-bag>가방</button><button data-restart>처음부터</button>${onExit?'<button data-exit>편집기로 · Esc</button>':''}</div><div class="actionViewport"><canvas aria-label="게임 화면"></canvas><div class="actionDialogue" hidden></div><div class="actionBag" hidden></div><div class="actionDead" hidden><h2>모험이 끝났어요</h2><button data-retry>다시 시작</button></div></div><div class="actionControls"><span>${Object.keys(bindings).map(k=>`${esc(keyLabel(k))} ${labels[k]}`).join(' · ')}</span>${Object.keys(bindings).filter(k=>k!=='bag').map(k=>`<button data-action="${k}">${labels[k]}</button>`).join('')}</div></div>`;
 const $=q=>root.querySelector(q),canvas=$('canvas'),ctx=canvas.getContext('2d'),view=$('.actionViewport'),dialog=$('.actionDialogue'),bag=$('.actionBag'),dead=$('.actionDead'),status=$('.actionStatus'),held=new Set(),edge=new Set(),pointers=new Map(),voices=new Set(),motions=new Map(),loops=new Map(),eventLoops=new Map();let audioMap, s,raf=0,last=performance.now(),moveClock=0,dialogSignature='',destroyed=false,paused=false;
 const has=(set,k)=>set.has('@'+k)||(bindings[k]||[]).some(code=>set.has(code));
 function stopLoop(key){const v=loops.get(key);if(v){v.audio.pause();voices.delete(v.audio);loops.delete(key);}}
 function stopAudio(){for(const audio of voices)audio.pause();voices.clear();loops.clear();}
 function playSound(id,scope){const asset=p.sounds?.find(a=>a.id===id);if(!asset||paused||document.hidden||!bag.hidden)return;if(scope&&loops.get(scope)?.id===id)return;if(scope)stopLoop(scope);if(voices.size>=16)return;const audio=new Audio(asset.data);audio.volume=asset.volume;audio.loop=!!scope;voices.add(audio);if(scope)loops.set(scope,{id,audio,failed:false});audio.onended=audio.onerror=()=>{voices.delete(audio);if(scope&&loops.get(scope)?.audio===audio)loops.get(scope).failed=true;};audio.play().catch(()=>{voices.delete(audio);if(scope&&loops.get(scope)?.audio===audio)loops.get(scope).failed=true;});}
 function sound(k){const id=p.soundBindings?.[k];if(!p.sounds?.find(a=>a.id===id)?.loop)playSound(id);}
 function syncLoops(wanted){for(const key of loops.keys())if(!wanted.has(key)||wanted.get(key)!==loops.get(key).id)stopLoop(key);for(const [key,id] of wanted)playSound(id,key);}
 function reset(){stopAudio();motions.clear();eventLoops.clear();audioMap=null;s=action?A.create(p):E.createState(p);s.time=0;s.effectState={};held.clear();edge.clear();pointers.clear();bag.hidden=true;dead.hidden=true;dialogSignature='';moveClock=0;last=performance.now();}
 function bagView(){bag.innerHTML='<b>소지품</b>'+Object.entries(s.inventory).filter(([,v])=>v>0).map(([k,v])=>`<p>${esc(k)} × ${v}</p>`).join('')+`<p>${esc(keyLabel('bag'))} 또는 가방 버튼으로 닫기</p>`;}
 function key(code,repeat=false){for(const [k,v] of loops)if(v.failed)stopLoop(k);if(code==='Escape'&&onExit){onExit();return;}if(code==='@bag'||bindings.bag?.includes(code)){if(!repeat){bag.hidden=!bag.hidden;bagView();held.clear();edge.clear();stopAudio();}return;}if(!bag.hidden||s.dead)return;if(s.dialog){if(repeat)return;if(s.dialog.type==='choice'&&/^Digit[1-4]$/.test(code))E.choose(p,s,+code.slice(-1)-1);else if(s.dialog.type==='text'&&(code==='@interact'||bindings.interact?.includes(code)))E.next(p,s);if(action)A.enter(p,s);return;}held.add(code);if(!repeat)edge.add(code);}
 function down(e){if(!root.isConnected||destroyed)return;e.stopImmediatePropagation();if(e.ctrlKey||e.metaKey||e.altKey)return;const code=e.code||({ ' ':'Space',Enter:'Enter',Escape:'Escape'}[e.key]||e.key);if(code==='Escape'||Object.values(bindings).some(keys=>keys.includes(code))||/^Digit[1-4]$/.test(code)){e.preventDefault();key(code,e.repeat);}}
 function up(e){held.delete(e.code);}
 function clear(){held.clear();edge.clear();pointers.clear();paused=true;stopAudio();}
 function focus(){paused=false;last=performance.now();}
 function visibility(){if(document.hidden)clear();else focus();}
 function paintDialogue(){const sig=JSON.stringify(s.dialog);if(sig===dialogSignature)return;dialogSignature=sig;dialog.hidden=!s.dialog;if(!s.dialog){dialog.innerHTML='';return;}held.clear();edge.clear();const d=s.dialog,portrait=p.assets.find(a=>a.id===d.portrait);dialog.innerHTML=(portrait?`<img alt="" src="${esc(portrait.gifData||portrait.data)}">`:'')+(d.speaker?`<b>${esc(d.speaker)}</b>`:'')+`<p>${esc(d.text)}</p>`+(d.type==='choice'?d.options.map((o,i)=>`<button data-choice="${i}">${i+1}. ${esc(o.label)}</button>`).join(''):`<small>${esc(keyLabel('interact'))} 또는 클릭해서 계속</small>`);dialog.querySelectorAll('[data-choice]').forEach(b=>b.onclick=e=>{e.stopPropagation();E.choose(p,s,+b.dataset.choice);if(action)A.enter(p,s);});}
 function loop(now){if(destroyed)return;const dt=Math.min((now-last)/1000,1/30);last=now;const w=Math.max(320,view.clientWidth),h=Math.max(200,view.clientHeight);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}
 const wanted=new Map();if(!paused&&!document.hidden&&bag.hidden){if(audioMap!==s.map){stopAudio();eventLoops.clear();motions.clear();audioMap=s.map;}if(action){const oldGrab=s.grab;A.tick(p,s,dt,{prone:has(held,'prone'),left:has(held,'left'),right:has(held,'right'),jump:has(edge,'jump'),attack:has(edge,'attack'),escape:has(edge,'escape'),heal:has(edge,'heal'),interact:has(edge,'interact')});if(oldGrab&&!s.grab)playSound(p.soundBindings?.escape);const actors=[['player',s],...(s.enemyMaps[s.map]||[]).filter(n=>n.hp>0).map(n=>[s.map+':'+n.id,n])];for(const [id,b] of actors){if(motions.get(id)!==b.anim){if(motions.has(id)||b.anim!=='idle')sound(b.anim);motions.set(id,b.anim);}const snd=p.soundBindings?.[b.anim];if(!s.dialog&&!s.dead&&p.sounds?.find(a=>a.id===snd)?.loop)wanted.set('motion:'+id,snd);}for(const id of motions.keys())if(!actors.some(a=>a[0]===id))motions.delete(id);}else if(!s.dialog){s.time+=dt;moveClock-=dt;const dirs={left:[-1,0],right:[1,0],up:[0,-1],down:[0,1]},k=Object.keys(dirs).find(k=>has(held,k));if(k&&(moveClock<=0||has(edge,k))){if(E.move(p,s,...dirs[k])){sound('run');s.lastMove=s.time;}moveClock=.12;}if(has(edge,'interact'))E.interact(p,s);const snd=p.soundBindings?.[k&&s.time-(s.lastMove??-1)<.15?'run':'idle'];if(p.sounds?.find(a=>a.id===snd)?.loop)wanted.set('motion:player',snd);}
 if(has(edge,'interact')&&!s.grab)playSound(p.soundBindings?.interact);if(audioMap!==s.map){stopAudio();eventLoops.clear();wanted.clear();motions.clear();audioMap=s.map;}for(const ev of s.audioEvents||[]){const id=typeof ev==='string'?ev:ev.id;if(ev.stop){eventLoops.delete(id);stopLoop('event:'+id);}else if(p.sounds?.find(a=>a.id===id)?.loop)eventLoops.set(id,id);else playSound(id);}s.audioEvents=[];if(s.dead){eventLoops.clear();wanted.clear();}for(const id of eventLoops.keys())wanted.set('event:'+id,id);syncLoops(wanted);}
 edge.clear();if(action){A.draw(ctx,p,s,w,h);status.textContent=s.grab?`잡힘 · ${keyLabel('escape')} 탈출 ${s.grab.presses}/${s.grab.required} · ${s.grab.time.toFixed(1)}초`:s.healCast?`회복 시전 ${s.healCast.toFixed(1)}초 · 체력 ${s.hp}/${A.config(p).hp}`:`체력 ${s.hp}/${A.config(p).hp}`;dead.hidden=!s.dead;}else{const m=p.maps.find(m=>m.id===s.map),sz=32,cx=Math.max(0,Math.min(m.w*sz-w,(s.x+.5)*sz-w/2)),cy=Math.max(0,Math.min(m.h*sz-h,(s.y+.5)*sz-h/2));ctx.clearRect(0,0,w,h);ctx.save();ctx.translate(-cx,-cy);E.drawMap(ctx,p,m,sz,{events:false,state:s});ctx.restore();status.textContent=m.name;}
 A.effects(ctx,p,s,w,h,paused||!bag.hidden||s.dialog?0:dt);paintDialogue();if(!bag.hidden)bagView();raf=requestAnimationFrame(loop);}
 dialog.onclick=()=>{if(s.dialog?.type==='text'){E.next(p,s);if(action)A.enter(p,s);}};$('[data-bag]').onclick=()=>key('@bag');$('[data-restart]').onclick=reset;$('[data-retry]').onclick=reset;if(onExit)$('[data-exit]').onclick=onExit;
 root.querySelectorAll('[data-action]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);pointers.set(e.pointerId,'@'+b.dataset.action);key('@'+b.dataset.action);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=e=>{const k=pointers.get(e.pointerId);pointers.delete(e.pointerId);if(![...pointers.values()].includes(k))held.delete(k);};});
 document.addEventListener('keydown',down,true);document.addEventListener('keyup',up,true);document.addEventListener('visibilitychange',visibility);window.addEventListener('blur',clear);window.addEventListener('focus',focus);reset();raf=requestAnimationFrame(loop);
 return {get state(){return s;},reset,destroy(){destroyed=true;stopAudio();cancelAnimationFrame(raf);document.removeEventListener('keydown',down,true);document.removeEventListener('keyup',up,true);document.removeEventListener('visibilitychange',visibility);window.removeEventListener('blur',clear);window.removeEventListener('focus',focus);root.innerHTML='';}};
 }
 return {mount};
}
if(typeof module!=='undefined')module.exports=GamePlayerFactory;else window.GamePlayer=GamePlayerFactory(window.Engine,window.Action);
