'use strict';
const https=require('node:https'),fs=require('node:fs/promises'),path=require('node:path'),crypto=require('node:crypto');
const VERSION=/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/;
function repository(value){if(typeof value!=='string'||!/^[-a-zA-Z0-9_]+\/[-a-zA-Z0-9_.]+$/.test(value))throw Error('아직 GitHub 배포 저장소가 연결되지 않았습니다.');return value;}
function newer(a,b){if(!VERSION.test(a)||!VERSION.test(b))throw Error('버전 형식이 잘못되었습니다.');const av=a.split('.').map(Number),bv=b.split('.').map(Number);for(let i=0;i<3;i++){if(av[i]!==bv[i])return av[i]>bv[i]}return false;}
function validateManifest(m,repo){repository(repo);if(!m||m.format!=='story-forge-update-v1'||m.repository!==repo||!VERSION.test(m.version)||m.asset!=='StoryForge-Setup.exe'||!Number.isSafeInteger(m.size)||m.size<1024||m.size>1024*1024*1024||!/^[0-9a-f]{64}$/.test(m.sha256))throw Error('업데이트 정보가 올바르지 않습니다.');return {format:m.format,repository:repo,version:m.version,asset:m.asset,size:m.size,sha256:m.sha256,notes:String(m.notes||'').slice(0,4000),url:`https://github.com/${repo}/releases/download/v${m.version}/${m.asset}`};}
function safeURL(value){const u=new URL(value);const allowed=['github.com','api.github.com','release-assets.githubusercontent.com','objects.githubusercontent.com'];if(u.protocol!=='https:'||!allowed.includes(u.hostname)||u.username||u.password||u.port&&u.port!=='443')throw Error('허용되지 않은 업데이트 주소입니다.');return u;}
function response(url,redirects=0){return new Promise((resolve,reject)=>{let settled=false;const fail=e=>{if(!settled){settled=true;reject(e)}};let req;try{req=https.get(safeURL(url),{headers:{'User-Agent':'StoryForge-Updater','Accept':'application/octet-stream'}},res=>{if([301,302,303,307,308].includes(res.statusCode)){res.resume();if(redirects>=5)return fail(Error('업데이트 주소 이동이 너무 많습니다.'));let next;try{next=new URL(res.headers.location,url).href;safeURL(next)}catch(e){return fail(e)}settled=true;resolve(response(next,redirects+1));return;}if(res.statusCode!==200){res.resume();return fail(Error(res.statusCode===404?'아직 공개된 업데이트가 없거나 배포 저장소에 접근할 수 없습니다.':`업데이트 서버 응답 오류 (${res.statusCode})`));}settled=true;resolve(res)});req.setTimeout(30000,()=>req.destroy(Error('업데이트 서버 응답이 늦습니다. 다시 시도해 주세요.')));req.on('error',fail)}catch(e){fail(e)}})}
async function readManifest(repo,transport=response){const r=repository(repo),res=await transport(`https://github.com/${r}/releases/latest/download/latest.json`);const chunks=[];let size=0;for await(const c of res){size+=c.length;if(size>16384){res.destroy?.();throw Error('업데이트 정보 파일이 너무 큽니다.')}chunks.push(c)}let raw;try{raw=JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{throw Error('업데이트 정보 파일을 읽을 수 없습니다.')}return validateManifest(raw,r)}
async function download(m,dir,progress=()=>{},transport=response){m=validateManifest(m,m.repository);await fs.mkdir(dir,{recursive:true});const final=path.join(dir,`StoryForge-${m.version}.exe`),tmp=final+'.partial';let file,total=0;try{file=await fs.open(tmp,'w',0o600);const res=await transport(m.url),hash=crypto.createHash('sha256');for await(const chunk of res){total+=chunk.length;if(total>m.size){res.destroy?.();throw Error('업데이트 파일 크기가 일치하지 않습니다.')}hash.update(chunk);await file.writeFile(chunk);progress(Math.floor(total/m.size*100))}await file.close();file=null;if(total!==m.size||hash.digest('hex')!==m.sha256)throw Error('업데이트 파일 검증에 실패했습니다. 다시 다운로드해 주세요.');const h=await fs.open(tmp,'r');const b=Buffer.alloc(2);await h.read(b,0,2,0);await h.close();if(b.toString()!=='MZ')throw Error('Windows 설치 파일이 아닙니다.');await fs.rename(tmp,final);return final}catch(e){if(file)await file.close().catch(()=>{});await fs.unlink(tmp).catch(()=>{});throw e}}
async function verify(file,m){const bytes=await fs.readFile(file);if(bytes.length!==m.size||crypto.createHash('sha256').update(bytes).digest('hex')!==m.sha256)throw Error('다운로드한 업데이트가 변경되었습니다. 다시 받아주세요.');}
function createUpdater({app,win,config,spawn,saveProject,onInstalling}){let state={status:config.repository?'idle':'unconfigured',currentVersion:app.getVersion(),repository:config.repository||null},manifest=null,installer=null,busy=false;function send(patch){state={...state,...patch};if(!win.isDestroyed())win.webContents.send('update:status',state)}return {
 state:()=>({...state}),
 async check(){if(busy)return state;busy=true;try{send({status:'checking',message:'새 버전을 확인하고 있어요.',progress:0});manifest=await readManifest(config.repository);installer=null;send({status:newer(manifest.version,app.getVersion())?'available':'current',version:manifest.version,notes:manifest.notes,message:newer(manifest.version,app.getVersion())?'새 버전을 받을 수 있어요.':'최신 버전입니다.'})}catch(e){send({status:'error',message:e.message})}finally{busy=false}return state},
 async download(){if(busy||!manifest||!newer(manifest.version,app.getVersion()))return state;busy=true;try{send({status:'downloading',message:'업데이트를 받고 있어요.',progress:0});installer=await download(manifest,path.join(app.getPath('userData'),'updates'),progress=>send({progress}));send({status:'ready',message:'저장하고 업데이트할 준비가 됐어요.',progress:100})}catch(e){send({status:'error',message:e.message});installer=null}finally{busy=false}return state},
 async install(projectText){if(busy||state.status!=='ready'||!installer)throw Error('먼저 업데이트를 다운로드해 주세요.');if(process.platform!=='win32'||!app.isPackaged)throw Error('설치된 Windows 앱에서만 업데이트를 적용할 수 있습니다.');busy=true;try{await verify(installer,manifest);await saveProject(projectText);const child=spawn(installer,['/S',`/UPGRADEPID=${process.pid}`,'/RELAUNCH',`/D=${path.dirname(process.execPath)}`],{detached:true,stdio:'ignore',windowsHide:true});await new Promise((ok,bad)=>{child.once('spawn',ok);child.once('error',bad)});child.unref();send({status:'installing',message:'프로젝트를 저장했어요. 업데이트 후 다시 열립니다.'});onInstalling();app.quit();return true}catch(e){busy=false;send({status:'error',message:e.message});throw e}}
 }}
module.exports={newer,repository,validateManifest,safeURL,readManifest,download,verify,createUpdater};
